/* Engine tests.
 *
 * Internal oracle: reference/golden.json, generated by reference/reference.py
 * (a transcription of the same MATLAB models).  That catches port errors but NOT
 * a physics mistake both ports share, so the external anchors in
 * reference/external/ (EPC AN030, EPC AN017, the committed datasheets) carry the
 * physics-level checks, and the N-scaling tests check structure that no golden
 * can catch.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import { loadEngine, loadJSON, assertClose } from './_harness.mjs';

const E = loadEngine();
const G = loadJSON('reference', 'golden.json');
const AN030 = loadJSON('reference', 'external', 'an030.json');
const AN017 = loadJSON('reference', 'external', 'an017.json');
const DS = loadJSON('reference', 'external', 'datasheet_anchors.json');

const TERMS = ['cond', 'overlap', 'coss', 'dead', 'qrr', 'ring', 'gate'];

/* ------------------------------------------------------------------ oracle */
test('seed library matches the oracle device data, field for field', () => {
  for (const [pn, p] of Object.entries(G.parts)) {
    assert.ok(E.PARTS[pn], 'missing seeded part ' + pn);
    for (const k of Object.keys(p)) assertClose(E.PARTS[pn][k], p[k], 'parts.' + pn + '.' + k);
  }
});

test('loss breakdown matches the oracle for every topology/temperature case', () => {
  let n = 0;
  for (const c of G.cases) {
    const r = E.computeLosses(E.PARTS[c.part], c.op, c.N, { tempMode: c.temp_mode });
    assertClose({
      terms: r.terms, die: r.die, driver: r.driver, total: r.total,
      eff: r.eff, Tj: r.Tj, converged: r.converged, rdson: r.rdson,
    }, c.expected, c.name);
    n++;
  }
  assert.ok(n >= 30, 'expected a meaningful number of cases, ran ' + n);
});

test('FOM metrics match the oracle', () => {
  for (const f of G.fom) {
    const r = E.fomMetrics(E.PARTS[f.part], f.op, f.N, 1.25);
    assertClose(r, f.expected, f.name);
  }
});

test('DeviceFOM.m-convention rows reproduce exactly', () => {
  for (const d of G.devicefom) {
    const r = E.fomMetrics(E.PARTS[d.part], d.op, 4, 1.25);
    assertClose(r.R1 * 1e3, d.R1_hot_mOhm, d.part + '.R1_hot_mOhm');
    assertClose(r.eOv, d.eOv_uJ_per_A, d.part + '.eOv_uJ_per_A');
    assertClose(r.Nopt, d.Nopt, d.part + '.Nopt');
    assertClose(r.Nint, d.Nint, d.part + '.Nint');
    assertClose(r.penaltyPct, d.penaltyPct, d.part + '.penaltyPct');
    assertClose(r.Nmin, d.Nmin, d.part + '.Nmin');
    assertClose(r.floor, d.floor, d.part + '.floor');
    assertClose(r.FOM_HS, d.FOM_HS, d.part + '.FOM_HS');
    assertClose(r.FOM_SS, d.FOM_SS, d.part + '.FOM_SS');
  }
});

test('EPC2361 Nopt reproduces Fsw_Optimum_Lehner7050.m\'s independently obtained N=4', () => {
  const f = E.fomMetrics(E.PARTS.EPC2361, G.devicefom[0].op, 4, 1.25);
  assert.equal(f.Nint, 4,
    'Fsw_Optimum_Lehner7050.m states N=4 comes out of Npar_Optimum.m; got Nint=' + f.Nint);
});

/* ------------------------------------------------- structural: N-scaling
 * A factor-of-N error is invisible to the oracle because both ports are
 * transcribed from the same text.  These assert the realised exponent against
 * the documented table instead. */
test('per-term N-scaling matches the documented exponent table', () => {
  for (const s of G.scaling) {
    const part = E.PARTS[s.part];
    const at = {};
    for (const n of s.N) at[n] = E.computeLosses(part, s.op, n, { tempMode: 'flat', kT: 1.0 }).terms;
    for (const k of TERMS) {
      assertClose(at[1][k], s[k + '_N1'], s.part + '.' + k + '.N1');
      assertClose(at[4][k], s[k + '_N4'], s.part + '.' + k + '.N4');
      if (s[k] === null || !(at[1][k] > 0) || !(at[4][k] > 0)) continue;
      const slope = Math.log(at[4][k] / at[1][k]) / Math.log(4);
      const [lo, hi] = s.expected_exp[k];
      assert.ok(slope >= lo - 1e-6 && slope <= hi + 1e-6,
        s.part + '.' + k + ' realised N-exponent ' + slope.toFixed(4) +
        ' is outside the documented range [' + lo + ', ' + hi + ']');
    }
  }
});

test('conduction falls as 1/N, overlap scales N (discrete) or N^0 (bridge), Coss and gate scale N', () => {
  for (const s of G.scaling) {
    const part = E.PARTS[s.part];
    const t1 = E.computeLosses(part, s.op, 1, { tempMode: 'flat', kT: 1.0 }).terms;
    const t4 = E.computeLosses(part, s.op, 4, { tempMode: 'flat', kT: 1.0 }).terms;
    assertClose(t4.cond / t1.cond, 0.25, s.part + ' conduction 1/N');
    if (s.kind === 'discrete') assertClose(t4.overlap / t1.overlap, 4, s.part + ' overlap ~N');
    else assertClose(t4.overlap / t1.overlap, 1, s.part + ' overlap ~N^0');
    assertClose(t4.coss / t1.coss, 4, s.part + ' coss ~N');
    assertClose(t4.gate / t1.gate, 4, s.part + ' gate ~N');
    // dead time must FALL with N (paralleling lowers the reverse drop)
    assert.ok(t4.dead < t1.dead, s.part + ' dead-time loss should fall with N, got ' +
      t1.dead + ' -> ' + t4.dead);
  }
});

test('Nopt is the integer minimiser of the closed-form A/N + B*N', () => {
  for (const f of G.fom) {
    const op = Object.assign({}, f.op, { gateModel: 'fom' });
    const r = E.fomMetrics(E.PARTS[f.part], op, f.N, 1.25);
    let best = 1, bv = Infinity;
    for (let n = 1; n <= 80; n++) {
      const v = r.A / n + n * (op.fsw * r.a + r.Pstat) + op.fsw * r.b;
      if (v < bv) { bv = v; best = n; }
    }
    assert.equal(best, r.Nint, f.part + ': argmin ' + best + ' != Nint ' + r.Nint);
  }
});

test('conduction in the breakdown equals A/N, and the Nopt penalty is the quadratic-flatness law', () => {
  for (const f of G.fom) {
    const part = E.PARTS[f.part];
    const op = Object.assign({}, f.op, { gateModel: 'fom', RthMode: 'flat', kT: 1.0 });
    const r = E.fomMetrics(part, op, f.N, 1.0);
    const tot = E.computeLosses(part, op, f.N, { tempMode: 'flat', kT: 1.0 });
    assertClose(tot.terms.cond, r.A / f.N, f.part + ' conduction == A/N');
    const pen = (0.5 * (r.Nopt / r.Nint + r.Nint / r.Nopt) - 1) * 100;
    assertClose(r.penaltyPct, pen, f.part + ' penalty');
  }
});

/* --------------------------------------------------------------- thermal */
test('thermal loop converges, and reports runaway instead of emitting a number', () => {
  for (const t of G.thermal) {
    const r = E.computeLosses(E.PARTS[t.part], t.op, t.N, { tempMode: 'converged' });
    assertClose({ Tj: r.Tj, converged: r.converged, gain: r.gain, rdson: r.rdson,
                  die: r.die, total: r.total }, t.expected, t.name);
    if (t.name === 'runaway') {
      assert.equal(r.converged, false, 'runaway case must report converged=false');
      assert.ok(!Number.isFinite(r.Tj), 'runaway case must not emit a junction temperature');
      const w = r.warnings.find(x => x.code === 'thermal_runaway');
      assert.ok(w, 'must warn about thermal runaway');
      assert.equal(w.severity, 'critical', 'runaway must be critical severity');
    }
  }
});

test('self-heating raises Tj and Rds above the 25 C value, and converges to a fixed point', () => {
  const op = { topology: 'threephase', Vdc: 58, fsw: 40000, Irms: 165.4, M: 1, PF: 0.9,
               Tamb: 25, tauDead: 4e-8, Vdrv: 5, Ron: 2.6, Roff: 0.6, kSoftOff: 0.22,
               RthMode: 'detailed', RthCA: 1, RthSink: 0.2, kTperC: 0.006, Lcsi: 0 };
  const cold = E.computeLosses(E.PARTS.EPC2361, op, 4, { tempMode: 'none' });
  const hot = E.computeLosses(E.PARTS.EPC2361, op, 4, { tempMode: 'converged' });
  assert.ok(hot.Tj > 25, 'converged Tj must exceed ambient');
  assert.ok(hot.rdson > cold.rdson, 'hot Rds(on) must exceed the 25 C value');
  // fixed point: recomputing at the reported Tj reproduces the same Tj
  const again = E.computeLosses(E.PARTS.EPC2361, op, 4, { tempMode: 'converged' });
  assertClose(again.Tj, hot.Tj, 'thermal fixed point', 1e-12, 1e-9);
});

test('the three-term thermal model differs from the single-Rth collapse', () => {
  // kTperC = 0 so Rds(on) is temperature-independent and the two modes dissipate
  // the SAME power: the difference is then exactly the per-die JC rise, which a
  // single-Rth collapse (RthCA + RthSink*nPos) omits entirely.
  const base = { topology: 'threephase', Vdc: 58, fsw: 40000, Irms: 165.4, M: 1, PF: 0.9,
                 Tamb: 25, tauDead: 4e-8, Vdrv: 5, Ron: 2.6, Roff: 0.6, kSoftOff: 0.22,
                 RthMode: 'detailed', RthCA: 1, RthSink: 0.5, kTperC: 0, Lcsi: 0 };
  const detailed = E.computeLosses(E.PARTS.EPC2361, base, 4, { tempMode: 'converged' });
  const simple = E.computeLosses(E.PARTS.EPC2361, Object.assign({}, base, { RthMode: 'simple' }),
                                 4, { tempMode: 'converged' });
  assert.ok(detailed.Tj !== simple.Tj, 'the Rth model choice must actually matter');
  assert.ok(detailed.Tj > simple.Tj,
    'omitting the per-die JC term must under-state Tj, got detailed=' + detailed.Tj +
    ' simple=' + simple.Tj);
  const diff = detailed.Tj - simple.Tj;
  const expectedDiff = (E.PARTS.EPC2361.RthJC / 4) * (detailed.die / 6);
  assertClose(diff, expectedDiff, 'JC contribution is RthJC/N * P_per_position', 1e-9, 1e-9);
});

test('the per-die JC term divides by N, instead of applying RthJC to the whole group', () => {
  // The reviewer's failure mode: Tj = Tamb + RthJC*P_group, i.e. forgetting the
  // /N, over-states heating by roughly N.  This pins the /N.
  const op = { topology: 'threephase', Vdc: 58, fsw: 40000, Irms: 165.4, M: 1, PF: 0.9,
               Tamb: 25, tauDead: 4e-8, Vdrv: 5, Ron: 2.6, Roff: 0.6, kSoftOff: 0.22,
               RthMode: 'detailed', RthCA: 0, RthSink: 0, kTperC: 0, Lcsi: 0 };
  const N = 4;
  const r = E.computeLosses(E.PARTS.EPC2361, op, N, { tempMode: 'converged' });
  const pPos = r.die / 6;                       // 6 switch positions, matched
  const riseModel = (E.PARTS.EPC2361.RthJC / N) * pPos;
  const riseNaive = E.PARTS.EPC2361.RthJC * pPos;   // the no-/N mistake
  assertClose(r.Tj - 25, riseModel, 'model rise is RthJC/N * P_pos', 1e-9, 1e-9);
  assertClose(riseNaive / riseModel, N, 'the naive form over-states the rise by N');
});

/* ------------------------------------------------------ external: AN030 */
test('AN030: turn-on and the current-fall phase match EPC\'s method exactly', () => {
  const c = AN030.case;
  const op = { topology: 'buck', Vin: c.Vbus, Vout: 24, Pout: 24 * c.I, fsw: c.fsw,
               Tamb: 25, tauDead: 4e-8, Vdrv: c.Vdrv, Ron: c.Ron, Roff: c.Roff,
               gateModel: 'fom', RthMode: 'flat', kT: 1, Lcsi: 0, L: null };
  const ex = AN030.engine_check;
  // kSoftOff = 0 strips the soft voltage-rise residual, isolating the two HARD
  // phases: turn-on (AN030 2.1) plus the gate-limited current fall (2.2.1).
  const r0 = E.computeLosses(E.PARTS[c.part], Object.assign({}, op, { kSoftOff: 0.0 }), 1,
                             { tempMode: 'flat', kT: 1 });
  assertClose(r0.terms.overlap / c.fsw, ex.Eon_plus_ifall_expected,
              'Eon + current-fall per cycle vs AN030');
  // kSoftOff = 1 reproduces AN030's FULL turn-off triangle
  const r1 = E.computeLosses(E.PARTS[c.part], Object.assign({}, op, { kSoftOff: 1.0 }), 1,
                             { tempMode: 'flat', kT: 1 });
  assertClose(r1.terms.overlap / c.fsw, ex.overlap_kSoftOff_1p0_expected,
              'overlap per cycle at kSoftOff=1.0');
  assertClose(r1.terms.overlap / c.fsw, ex.overlap_kSoftOff_1p0_AN030_naive,
              'at kSoftOff=1 the engine must reproduce AN030 exactly', 1e-12);
});

test('AN030: the turn-off current fall is hard, and kSoftOff scales only the voltage rise', () => {
  const c = AN030.case;
  const op = { topology: 'buck', Vin: c.Vbus, Vout: 24, Pout: 24 * c.I, fsw: c.fsw,
               Tamb: 25, tauDead: 4e-8, Vdrv: c.Vdrv, Ron: c.Ron, Roff: c.Roff,
               gateModel: 'fom', RthMode: 'flat', kT: 1, Lcsi: 0, L: null };
  const part = E.PARTS[c.part];
  const e = k => E.computeLosses(part, Object.assign({}, op, { kSoftOff: k }), 1,
                                 { tempMode: 'flat', kT: 1 }).terms.overlap / c.fsw;
  const e0 = e(0.0), e1 = e(1.0);
  assertClose(e1 - e0, AN030.expected.Evrise_AN030,
              'kSoftOff must scale the voltage-rise phase and nothing else', 1e-12);
  assert.ok((e1 - e0) < 0.5 * e0, 'the soft phase is the smaller half at this point');
});

test('AN030: turn-off is below the naive triangle and matches the soft-turn-off expression', () => {
  const c = AN030.case;
  const op = { topology: 'buck', Vin: c.Vbus, Vout: 24, Pout: 24 * c.I, fsw: c.fsw,
               Tamb: 25, tauDead: 4e-8, Vdrv: c.Vdrv, Ron: c.Ron, Roff: c.Roff,
               gateModel: 'fom', RthMode: 'flat', kT: 1, Lcsi: 0, L: null };
  const r = E.computeLosses(E.PARTS[c.part], Object.assign({}, op, { kSoftOff: 0.22 }), 1,
                            { tempMode: 'flat', kT: 1 });
  assertClose(r.terms.overlap / c.fsw, AN030.engine_check.overlap_kSoftOff_0p22_expected,
              'overlap per cycle at kSoftOff=0.22');
  assert.ok(r.terms.overlap / c.fsw < AN030.expected.Eoverlap_AN030_naive,
            'the soft-turn-off refinement must sit below AN030\'s naive triangle');
});

test('AN030: symmetric half-bridge capacitive loss is Vbus*QOSS, and is exactly 3*Eoss', () => {
  const c = AN030.case;
  const op = { topology: 'buck', Vin: c.Vbus, Vout: 24, Pout: 24 * c.I, fsw: c.fsw,
               Tamb: 25, tauDead: 4e-8, Vdrv: c.Vdrv, Ron: c.Ron, Roff: c.Roff,
               gateModel: 'fom', RthMode: 'flat', kT: 1, Lcsi: 0, L: null };
  const part = E.PARTS[c.part];
  const vq = E.computeLosses(part, op, 1, { tempMode: 'flat', kT: 1, cossBasis: 'VQoss' });
  const eo = E.computeLosses(part, op, 1, { tempMode: 'flat', kT: 1, cossBasis: 'Eoss' });
  const e2 = E.computeLosses(part, op, 1, { tempMode: 'flat', kT: 1, cossBasis: '2Eoss' });
  assertClose(vq.terms.coss / c.fsw, AN030.engine_check.coss_VQoss_per_cycle, 'V*Qoss per cycle');
  assertClose(vq.terms.coss / eo.terms.coss, 3.0, 'V*Qoss / Eoss', 1e-12);
  assertClose(vq.terms.coss / e2.terms.coss, 1.5, 'V*Qoss / (2*Eoss)', 1e-12);
  assertClose(eo.terms.coss / c.fsw, AN030.engine_check.coss_Eoss_per_cycle, 'Eoss per cycle');
});

test('AN030: reverse recovery is QRR*Vbus*fsw, and exactly zero for every GaN part', () => {
  const c = AN030.case;
  const op = { topology: 'buck', Vin: c.Vbus, Vout: 24, Pout: 24 * c.I, fsw: c.fsw,
               Tamb: 25, tauDead: 4e-8, Vdrv: c.Vdrv, Ron: c.Ron, Roff: c.Roff,
               gateModel: 'fom', RthMode: 'flat', kT: 1, Lcsi: 0, L: null };
  const si = E.computeLosses(E.PARTS.IRF7759, op, 1, { tempMode: 'flat', kT: 1 });
  assertClose(si.terms.qrr / c.fsw, AN030.expected.Qrr_AN030_per_die, 'QRR per cycle (Si)');
  for (const [pn, p] of Object.entries(E.PARTS)) {
    if (p.technology !== 'GaN') continue;
    const r = E.computeLosses(p, op, 1, { tempMode: 'flat', kT: 1 });
    assert.equal(r.terms.qrr, 0, pn + ' is GaN and must have zero reverse-recovery loss');
  }
});

test('AN030: gate loss is QG*VGS outside the die, and is excluded from the die total', () => {
  const c = AN030.case;
  const op = { topology: 'buck', Vin: c.Vbus, Vout: 24, Pout: 24 * c.I, fsw: c.fsw,
               Tamb: 25, tauDead: 4e-8, Vdrv: c.Vdrv, Ron: c.Ron, Roff: c.Roff,
               gateModel: 'fom', RthMode: 'flat', kT: 1, Lcsi: 0, L: null };
  const r = E.computeLosses(E.PARTS[c.part], op, 1, { tempMode: 'flat', kT: 1 });
  assertClose(r.terms.gate / c.fsw, AN030.engine_check.gate_expected_2QGVdrv, 'gate per cycle');
  const dieSum = TERMS.filter(k => k !== 'gate' && k !== 'ring').reduce((s, k) => s + r.terms[k], 0);
  assertClose(r.die, dieSum, 'die excludes gate');
  assertClose(r.total, r.die + r.loop + r.driver, 'total = die + loop + driver');
});

/* ------------------------------------------------------ external: AN017 */
test('AN017: FOM_HS = (Qgd + Qgs2)*Rds(on) and FOM_SS = (Qg + Qoss)*Rds(on)', () => {
  const op = { topology: 'threephase', Vdc: 58, fsw: 40000, Irms: 165.4, M: 1, PF: 0.9,
               Tamb: 25, tauDead: 4e-8, Vdrv: 5, Ron: 2.6, Roff: 0.6, kSoftOff: 0.22,
               gateModel: 'fom', RthMode: 'flat', kT: 1, Lcsi: 0 };
  for (const [pn, row] of Object.entries(AN017.rows)) {
    const f = E.fomMetrics(E.PARTS[pn], op, 1, 1.0);
    assertClose(f.FOM_HS * 1e12, row.FOM_HS_mOhm_nC, pn + '.FOM_HS [mOhm*nC]');
    assertClose(f.FOM_SS * 1e12, row.FOM_SS_mOhm_nC, pn + '.FOM_SS [mOhm*nC]');
    // independent hand-check of the definition
    const p = E.PARTS[pn];
    assertClose(f.FOM_HS, (p.Qgd + (p.Qgs - p.Qgth)) * p.Rdson25, pn + '.FOM_HS definition');
  }
});

test('AN017: the GaN part beats the silicon part on the published hard-switching FOM', () => {
  const op = { topology: 'threephase', Vdc: 58, fsw: 40000, Irms: 165.4, M: 1, PF: 0.9,
               Tamb: 25, tauDead: 4e-8, Vdrv: 5, Ron: 2.6, Roff: 0.6, kSoftOff: 0.22,
               gateModel: 'fom', RthMode: 'flat', kT: 1, Lcsi: 0 };
  const g = E.fomMetrics(E.PARTS.EPC2361, op, 1, 1.0);
  const s = E.fomMetrics(E.PARTS.IRF7759, op, 1, 1.0);
  const ratio = s.FOM_HS / g.FOM_HS;
  assertClose(ratio, AN017.direction.FOM_HS_improvement_Si_over_GaN, 'improvement factor', 1e-6);
  assert.ok(ratio > 10, 'GaN should be a large factor better on FOM_HS, got ' + ratio.toFixed(1));
  assert.ok(g.R_E < s.R_E, 'GaN must also win the energy-based R*E figure of merit');
  assert.ok(g.eOv < s.eOv, 'GaN must win on overlap energy per commutated amp');
});

/* ------------------------------------------- external: primary datasheets */
test('seeded device data matches the datasheets committed in this repo', () => {
  for (const [pn, fields] of Object.entries(DS.expected)) {
    for (const [k, v] of Object.entries(fields)) {
      if (k === 'kind' || k === 'technology') { assert.equal(E.PARTS[pn][k], v, pn + '.' + k); continue; }
      assertClose(E.PARTS[pn][k], v, pn + '.' + k + ' (primary source)');
    }
  }
});

test('EPC2361 and ISG3202LA are flagged as carrying estimates where they do', () => {
  assert.ok(E.PARTS.ISG3202LA.est.includes('tsw'),
    'ISG3202LA publishes no Eon/Eoff, so its tsw must be flagged as an estimate');
  assert.ok(E.PARTS.EPC2361.est.includes('kTperC'));
  assert.ok(E.PARTS.IRF7759.est.includes('BVdss'));
});

/* ------------------------------------------------------------ behaviour */
test('GaN vs Si headline: silicon pays on overlap, Qrr, dead time and gate drive', () => {
  const op = { topology: 'threephase', Vdc: 58, fsw: 40000, Irms: 165.4, M: 1, PF: 0.9,
               Tamb: 25, tauDead: 4e-8, Vdrv: 5, Ron: 2.6, Roff: 0.6, kSoftOff: 0.22,
               RthMode: 'flat', kT: 1.25, Lcsi: 0 };
  const gan = E.computeLosses(E.PARTS.EPC2361, op, 4, { tempMode: 'flat' });
  const si = E.computeLosses(E.PARTS.IRF7759, op, 4, { tempMode: 'flat' });
  assertClose(gan.die, 38.53, 'EPC2361 die total [W]', 1e-4, 0.01);
  assertClose(si.die, 103.50, 'IRF7759 die total [W]', 1e-4, 0.01);
  assert.equal(gan.terms.qrr, 0);
  assert.ok(si.terms.qrr > 0, 'silicon must show a reverse-recovery penalty');
  assert.ok(si.terms.overlap > 3 * gan.terms.overlap, 'silicon overlap should be far worse');
  assert.ok(si.terms.gate > 10 * gan.terms.gate, 'silicon gate drive should be far worse');
  assert.ok(si.die > 2 * gan.die, 'overall silicon die loss should be much higher here');
});

test('compare() exposes the chosen-N and each-at-its-own-Nopt views plus the N-invariant FOM', () => {
  const op = E.defaultOp('threephase');
  const c = E.compare(E.PARTS.EPC2361, E.PARTS.IRF7759, op, 4, { tempMode: 'flat' });
  assert.equal(c.sharedN.length, 2);
  assert.equal(c.eachOpt.length, 2);
  // a plain number means the same count for both, the original form
  assert.equal(c.N.A, 4);
  assert.equal(c.N.B, 4);
  assert.ok(c.Nopt.A >= 1 && c.Nopt.B >= 1);
  assert.ok(c.fom.A.R_E < c.fom.B.R_E, 'R*E ranking must favour GaN');
  // the two views must be allowed to disagree, which is the whole point
  assert.ok(c.fom.A.Nopt !== c.fom.B.Nopt || c.Nopt.A !== c.Nopt.B);
});

test('compare() accepts a per-device parallel count (4 GaN against 2 Si)', () => {
  const op = E.defaultOp('threephase');
  const N = { A: 4, B: 2 };
  const c = E.compare(E.PARTS.EPC2361, E.PARTS.IRF7759, op, N, { tempMode: 'flat' });
  assert.equal(c.N.A, 4);
  assert.equal(c.N.B, 2);
  // the chosen count must actually reach the loss model per device
  const a = E.computeLosses(E.PARTS.EPC2361, op, 4, { tempMode: 'flat', slot: 'A' });
  const b = E.computeLosses(E.PARTS.IRF7759, op, 2, { tempMode: 'flat', slot: 'B' });
  assertClose(c.sharedN[0].total, a.total, 'A evaluated at its own N=4');
  assertClose(c.sharedN[1].total, b.total, 'B evaluated at its own N=2');
  // conduction falls 1/N, so halving B's dice must raise its conduction loss
  const b4 = E.computeLosses(E.PARTS.IRF7759, op, 4, { tempMode: 'flat', slot: 'B' });
  assert.ok(c.sharedN[1].terms.cond > b4.terms.cond,
            'N=2 must conduct more than N=4 for the same part');
  // nOf is the documented resolver, and a partial object defaults the rest
  assert.equal(E.nOf(N, 'A'), 4);
  assert.equal(E.nOf(N, 'B'), 2);
  assert.equal(E.nOf({ A: 6 }, 'B'), 1);
  assert.equal(E.nOf(5, 'A'), 5);
});

test('efficiency is Pout/(Pout+total), and the lower-loss part has the higher eta', () => {
  const op = E.defaultOp('threephase');
  const c = E.compare(E.PARTS.EPC2361, E.PARTS.IRF7759, op, 4, { tempMode: 'flat' });
  const pout = c.sharedN[0].derived.Pout;
  assert.ok(pout > 0, 'the operating point must define a positive processed power');
  for (const r of c.sharedN) {
    assertClose(r.eff, pout / (pout + r.total), 'eta = Pout/(Pout+total)');
    assert.ok(r.eff > 0 && r.eff < 1, 'semiconductor-only eta must be a sane fraction');
  }
  assert.ok(c.sharedN[0].eff > c.sharedN[1].eff,
            'the lower-loss device must show the higher efficiency');
});

test('every topology computes and conserves energy', () => {
  const cases = [
    E.defaultOp('threephase'),
    E.defaultOp('buck'),
    E.defaultOp('boost'),
    E.defaultOp('fourswitch'),
  ];
  for (const op of cases) {
    for (const [pn, p] of Object.entries(E.PARTS)) {
      const r = E.computeLosses(p, op, 2, { tempMode: 'none' });
      for (const k of TERMS) {
        assert.ok(Number.isFinite(r.terms[k]), op.topology + '/' + pn + '.' + k + ' is not finite');
        assert.ok(r.terms[k] >= -1e-12, op.topology + '/' + pn + '.' + k + ' is negative');
      }
      const sum = TERMS.filter(k => k !== 'gate' && k !== 'ring').reduce((s, k) => s + r.terms[k], 0);
      assertClose(r.die, sum, op.topology + '/' + pn + ' die sum');
      assertClose(r.total, r.die + r.loop + r.driver, op.topology + '/' + pn + ' total');
    }
  }
});

test('fsw sweep and N sweep return monotone, finite, best-marked curves', () => {
  const op = E.defaultOp('threephase');
  const sw = E.sweepFsw(E.PARTS.EPC2361, op, 4, 10000, 200000, 24, { tempMode: 'flat' });
  assert.equal(sw.points.length, 24);
  assert.ok(sw.fopt >= 10000 && sw.fopt <= 200000);
  for (const p of sw.points) assert.ok(Number.isFinite(p.r.total));
  const on = E.optimizeN(E.PARTS.EPC2361, op, { tempMode: 'flat' }, 12);
  assert.equal(on.curve.length, 12);
  assert.ok(on.Nbest >= 1 && on.Nbest <= 12);
  assert.equal(on.curve.find(c => c.total === on.best).N, on.Nbest);
});

/* ------------------------------------------------------------ overrides */
test('advanced overrides: op-level qossExp and qrrExp beat the per-part value, without mutating the library', () => {
  const op = { topology: 'threephase', Vdc: 58, fsw: 40000, Irms: 165.4, M: 1, PF: 0.9,
               Tamb: 25, tauDead: 4e-8, Vdrv: 5, Ron: 2.6, Roff: 0.6, kSoftOff: 0.22,
               RthMode: 'flat', kT: 1.25, Lcsi: 0 };
  const flat = { tempMode: 'flat', kT: 1 };

  // qossExp: a steeper charge law stores more charge at 58 V than V^-0.5.
  const b = E.computeLosses(E.PARTS.EPC2361, op, 1, flat);
  const s = E.computeLosses(E.PARTS.EPC2361, Object.assign({}, op, { qossExp: 2 }), 1, flat);
  assert.ok(s.terms.coss > b.terms.coss,
    'qossExp override must change the Coss term (' + b.terms.coss + ' -> ' + s.terms.coss + ')');
  assert.equal(E.PARTS.EPC2361.qossExp, 0.5, 'the library part must NOT be mutated');

  // qrrExp: 1 makes Qrr linear in current, so the paralleled group total stops
  // scaling as N.  The default (0) scales as N.
  const p = E.PARTS.IRF7759;
  const d1 = E.computeLosses(p, op, 1, flat).terms.qrr;
  const d4 = E.computeLosses(p, op, 4, flat).terms.qrr;
  assertClose(d4 / d1, 4, 'default qrrExp=0 scales the group Qrr as N', 1e-9);
  const l1 = E.computeLosses(p, Object.assign({}, op, { qrrExp: 1 }), 1, flat).terms.qrr;
  const l4 = E.computeLosses(p, Object.assign({}, op, { qrrExp: 1 }), 4, flat).terms.qrr;
  assertClose(l4 / l1, 1, 'qrrExp=1 makes the group Qrr N-independent', 1e-9);
  assert.equal(p.qrrExp, 0, 'the library part must NOT be mutated');
});

/* ------------------------------------------------------------ warnings */
test('warnings are structured objects, not free text the UI has to parse', () => {
  const SEV = new Set(['critical', 'caution', 'info']);
  const three = { topology: 'threephase', Vdc: 58, fsw: 40000, Irms: 165.4, M: 1, PF: 0.9,
                  Tamb: 25, tauDead: 4e-8, Vdrv: 5, Ron: 2.6, Roff: 0.6, kSoftOff: 0.22,
                  RthMode: 'flat', kT: 1.25, Lcsi: 0 };
  const seen = {};
  const runs = [
    // IRF7759 asked for 5 V: at/below the 5 V plateau, so the auto-rail switch
    // fires and the model is evaluated at 12 V (which is >= its 10 V rating, so
    // there is deliberately NO under-drive warning here).
    E.computeLosses(E.PARTS.IRF7759, three, 1, { tempMode: 'flat' }),
    // IRF7759 asked for 8 V: above the plateau (no auto switch) but below the
    // 10 V rail Rds(on) is quoted at, which IS under-drive.
    E.computeLosses(E.PARTS.IRF7759, Object.assign({}, three, { Vdrv: 8 }), 1, { tempMode: 'flat' }),
    // thermal runaway
    E.computeLosses(E.PARTS.EPC2361, Object.assign({}, three,
      { RthMode: 'detailed', RthCA: 20, RthSink: 5, kTperC: 0.05 }), 1, { tempMode: 'converged' }),
    // 4-switch with Vin == Vout
    E.computeLosses(E.PARTS.EPC2361, Object.assign(E.defaultOp('fourswitch'),
      { Vin: 24, Vout: 24, Pout: 240, fsw: 200e3 }), 1, { tempMode: 'none' }),
    // switch node over the device rating
    E.computeLosses(E.PARTS.EPC2361, { topology: 'buck', Vin: 150, Vout: 24, Pout: 240,
      fsw: 100e3, Tamb: 25, tauDead: 4e-8 }, 1, { tempMode: 'none' }),
  ];
  for (const r of runs) {
    for (const w of r.warnings) {
      assert.ok(SEV.has(w.severity), 'bad severity: ' + JSON.stringify(w));
      assert.ok(typeof w.code === 'string' && w.code.length > 2, 'missing code');
      assert.ok(typeof w.title === 'string' && w.title.length > 3, 'missing title');
      assert.ok(typeof w.detail === 'string' && w.detail.length > 20, 'missing detail');
      // the old free-text form must be gone
      assert.equal(typeof w, 'object');
      seen[w.code] = w.severity;
    }
  }
  assert.equal(seen.gate_rail_auto, 'caution', 'expected the gate-rail auto-switch warning');
  assert.equal(seen.gate_underdrive, 'caution', 'expected the underdrive warning');
  assert.equal(seen.thermal_runaway, 'critical', 'expected thermal runaway');
  assert.equal(seen.mode_buckboost, 'caution', 'expected the buck-boost mode warning');
  assert.equal(seen.bvs_exceeded, 'critical', 'expected the rating warning');
});

/* ------------------------------------------------- per-device gate rails */
test('gateFor resolves each device to its own recommended rail', () => {
  for (const g of G.gates) {
    const got = E.gateFor(E.PARTS[g.part], g.op, g.slot).Vdrv;
    assertClose(got, g.expected, 'gateFor ' + g.part + ' slot=' + g.slot + ' (' + g.why + ')');
  }
  // The recommended rails are exactly why one shared rail cannot be right here.
  const op = E.defaultOp('threephase');
  assertClose(E.gateFor(E.PARTS.EPC2361, op, 'A').Vdrv, 5, 'GaN rail');
  assertClose(E.gateFor(E.PARTS.IRF7759, op, 'B').Vdrv, 10, 'Si rail');
  assertClose(E.gateFor(E.PARTS.IAUTN08S7N006ATMA1, op, 'A').Vdrv, 10, 'new Si rail');
  assertClose(E.gateFor(E.PARTS.EPC23102, op, 'B').Vdrv, 5, 'bridge default rail');
  const ov = Object.assign({}, op, { VdrvA: 12, VdrvB: 6 });
  assertClose(E.gateFor(E.PARTS.EPC2361, ov, 'A').Vdrv, 12, 'VdrvA override');
  assertClose(E.gateFor(E.PARTS.IRF7759, ov, 'B').Vdrv, 6, 'VdrvB override');
});

test("a Si/GaN comparison is evaluated at each part's own gate rail", () => {
  const op = E.defaultOp('threephase'), N = 4, fsw = op.fsw;
  const c = E.compare(E.PARTS.EPC2361, E.PARTS.IRF7759, op, N, { tempMode: 'flat' });
  const nPos = 2 * 3 * N;                       // 3 legs x 2 switch positions
  assertClose(c.sharedN[0].terms.gate, nPos * E.PARTS.EPC2361.Qg * 5 * fsw,
              'GaN gate loss at its 5 V rail');
  assertClose(c.sharedN[1].terms.gate, nPos * E.PARTS.IRF7759.Qg * 10 * fsw,
              'Si gate loss at its 10 V rail');
});

test('a shared 5 V rail under-drives a 10 V Si part; the per-device rail fixes it', () => {
  const op = E.defaultOp('threephase'), p = E.PARTS.IAUTN08S7N006ATMA1;
  const own = E.computeLosses(p, op, 4, { tempMode: 'none', slot: 'A' });
  const shared = E.computeLosses(p, Object.assign({}, op, { Vdrv: 5 }), 4,
                                 { tempMode: 'none', slot: 'A' });
  assertClose(E.gateFor(p, op, 'A').Vdrv, 10, 'own recommended rail');
  assertClose(E.gateFor(p, Object.assign({}, op, { Vdrv: 5 }), 'A').Vdrv, 5, 'shared rail wins');
  assert.ok(!own.warnings.some(w => w.code === 'gate_underdrive'),
            'its own 10 V rail must not under-drive');
  assert.ok(shared.warnings.some(w => w.code === 'gate_underdrive'),
            'a shared 5 V rail must flag the 10 V Si part as under-driven');
  assert.ok(shared.terms.overlap > own.terms.overlap,
            'under-drive inflates the overlap (' + own.terms.overlap + ' -> ' + shared.terms.overlap + ')');
});

test('the runaway path emits no numeric junction temperature anywhere', () => {
  const op = { topology: 'threephase', Vdc: 58, fsw: 40000, Irms: 165.4, M: 1, PF: 0.9,
               Tamb: 25, tauDead: 4e-8, Vdrv: 5, Ron: 2.6, Roff: 0.6, kSoftOff: 0.22,
               RthMode: 'detailed', RthCA: 20, RthSink: 5, kTperC: 0.05, Lcsi: 0 };
  const r = E.computeLosses(E.PARTS.EPC2361, op, 1, { tempMode: 'converged' });
  assert.ok(!Number.isFinite(r.Tj));
  assert.equal(r.converged, false);
});

test('the runaway guard is referenced to per-position conduction, not the whole bridge', () => {
  // Regression: the guard used whole-bridge conduction while the temperature
  // rise uses P_group/n_positions, overstating the gain by n_positions (6 here)
  // and inventing thermal runaway on a build that converges perfectly well.
  const op = { topology: 'threephase', Vdc: 58, fsw: 40000, Irms: 165.4, M: 1, PF: 0.9,
               Tamb: 25, tauDead: 4e-8, Vdrv: 5, Ron: 2.6, Roff: 0.6, kSoftOff: 0.22,
               RthMode: 'detailed', RthCA: 5, RthSink: 0.5, kTperC: 0.008, Lcsi: 0 };
  const part = E.PARTS.IRF7759, N = 4, nPos = 6;
  const cold = E.computeLosses(part, op, N, { tempMode: 'none' });
  const hot = E.computeLosses(part, op, N, { tempMode: 'converged' });
  assert.equal(hot.converged, true, 'a sane silicon build must not be reported as thermal runaway');
  assert.ok(hot.gain < 1, 'gain must be below 1, got ' + hot.gain);
  assert.ok(!hot.warnings.some(w => w.code === 'thermal_runaway'), 'must not warn runaway here');

  const rthRef = (part.RthJC / N + 5 + 0.5 * nPos) / nPos;   // referenced to P_group
  assertClose(hot.gain, rthRef * 0.008 * cold.terms.cond,
    'gain = Rth_ref * kTperC * P_cond_group at 25 C');
  const overstated = (part.RthJC / N + 5 + 0.5 * nPos) * 0.008 * cold.terms.cond;
  assertClose(overstated / hot.gain, nPos,
    'the un-divided form must overstate the gain by exactly the position count');
});

/* --------------------------------------- loop inductance, Tj limit, typ/max */
test('loop-inductance ringing is counted, and is independent of N', () => {
  const op = { topology: 'threephase', Vdc: 58, fsw: 40000, Irms: 165.4, M: 1, PF: 0.9,
               Tamb: 25, tauDead: 4e-8, Vdrv: 5, Ron: 2.6, Roff: 0.6, kSoftOff: 0.22,
               RthMode: 'flat', kT: 1, Lcsi: 0, Lloop: 5e-9 };
  const p = E.PARTS.EPC2361;
  const r1 = E.computeLosses(p, op, 1, { tempMode: 'flat', kT: 1 });
  const r4 = E.computeLosses(p, op, 4, { tempMode: 'flat', kT: 1 });
  const expect = 3 * op.fsw * 0.5 * 5e-9 * op.Irms * op.Irms;   // 3 legs, <i^2> = Irms^2
  assertClose(r1.terms.ring, expect, 'ringing magnitude at 5 nH', 1e-9);
  assertClose(r4.terms.ring, expect, 'ringing is N-independent once current is fixed', 1e-9);
  assert.ok(r4.terms.ring / r4.total > 0.15, 'at 5 nH this is not a small correction');
  assertClose(r4.total, r4.die + r4.loop + r4.driver, 'loop loss is outside the die total');
});

test('omitting L_loop is flagged, not silently under-reported', () => {
  const op = E.defaultOp('threephase');
  const r = E.computeLosses(E.PARTS.EPC2361, op, 4, { tempMode: 'flat' });
  const w = r.warnings.find(x => x.code === 'lloop_uncounted');
  assert.ok(w, 'must warn that loop ringing is uncounted');
  assert.equal(w.severity, 'info');
  assert.match(w.detail, /W here/, 'the caution should quantify it at a suggested 5 nH');
  const r2 = E.computeLosses(E.PARTS.EPC2361, Object.assign({}, op, { Lloop: 5e-9 }), 4, { tempMode: 'flat' });
  assert.ok(!r2.warnings.some(x => x.code === 'lloop_uncounted'), 'no caution once a value is set');
});

test('Qrr scales with junction temperature', () => {
  const op = { topology: 'threephase', Vdc: 58, fsw: 40000, Irms: 165.4, M: 1, PF: 0.9,
               Tamb: 25, tauDead: 4e-8, Vdrv: 5, Ron: 2.6, Roff: 0.6, kSoftOff: 0.22,
               RthMode: 'detailed', RthCA: 5, RthSink: 0.5 };
  const p = E.PARTS.IRF7759;
  const cold = E.computeLosses(p, op, 4, { tempMode: 'none' });      // Tj = 25 C
  const hot = E.computeLosses(p, op, 4, { tempMode: 'converged' });
  const factor = 1 + 0.01 * (hot.Tj - 25);
  assertClose(hot.terms.qrr / cold.terms.qrr, factor, 'Qrr(Tj) factor', 1e-9);
  assert.ok(hot.terms.qrr > 2 * cold.terms.qrr, 'hot Qrr should be well over 2x the 25 C value');
});

test('typ/max moves the model onto the datasheet maxima where they exist', () => {
  const base = Object.assign(E.defaultOp('threephase'), { RthMode: 'flat', kT: 1 });
  const typ = E.computeLosses(E.PARTS.IRF7759, Object.assign({}, base, { useMax: false }), 4, { tempMode: 'flat', kT: 1 });
  const mx = E.computeLosses(E.PARTS.IRF7759, Object.assign({}, base, { useMax: true }), 4, { tempMode: 'flat', kT: 1 });
  assert.ok(mx.terms.qrr > typ.terms.qrr, 'QrrMax must raise the recovery loss');
  // IRF7759 has no RdsonMax, so a partial application must be reported
  const w = mx.warnings.find(x => x.code === 'typ_max_partial');
  assert.ok(w, 'partial application must be reported');
  assert.match(w.detail, /RdsonMax/);
  // EPC2361 has RdsonMax and QossMax recorded
  const bt = E.computeLosses(E.PARTS.EPC2361, Object.assign({}, base, { useMax: false }), 4, { tempMode: 'flat', kT: 1 });
  const bm = E.computeLosses(E.PARTS.EPC2361, Object.assign({}, base, { useMax: true }), 4, { tempMode: 'flat', kT: 1 });
  assert.ok(bm.terms.cond > bt.terms.cond, 'RdsonMax must raise conduction');
  assert.ok(bm.terms.coss > bt.terms.coss, 'QossMax must raise the capacitive term');
});

test('a junction temperature past the device limit is a critical warning', () => {
  const op = Object.assign(E.defaultOp('threephase'), { RthMode: 'detailed', RthCA: 5, RthSink: 0.5 });
  const si = E.computeLosses(E.PARTS.IRF7759, op, 4, { tempMode: 'converged' });
  const w = si.warnings.find(x => x.code === 'tj_exceeded');
  assert.ok(w, 'the silicon build runs past its limit and must say so');
  assert.equal(w.severity, 'critical');
  assert.ok(si.Tj > E.PARTS.IRF7759.TjMax);
  const gan = E.computeLosses(E.PARTS.EPC2361,
    Object.assign({}, E.defaultOp('threephase'), { RthMode: 'detailed', RthCA: 1, RthSink: 0.2 }),
    4, { tempMode: 'converged' });
  assert.ok(!gan.warnings.some(x => x.code === 'tj_exceeded'), 'a comfortable build must not warn');
  for (const pn of Object.keys(E.PARTS)) assert.ok(E.PARTS[pn].TjMax > 100, pn + ' needs a TjMax');
});

/* ------------------------------------------------------------ persistence */
test('library and scenario JSON round-trip with the current schemaVersion', () => {
  // library contract
  const lib = JSON.parse(JSON.stringify({ schemaVersion: E.schemaVersion, parts: E.PARTS }));
  assert.equal(lib.schemaVersion, E.schemaVersion, 'library export must carry the current schemaVersion');
  assert.deepEqual(Object.keys(lib.parts).sort(), Object.keys(E.PARTS).sort());
  for (const pn of Object.keys(E.PARTS)) assertClose(lib.parts[pn], E.PARTS[pn], 'roundtrip.' + pn);
  // 'est' must survive, because it drives the estimate badges
  for (const pn of Object.keys(E.PARTS)) {
    assert.deepEqual(lib.parts[pn].est, E.PARTS[pn].est, pn + '.est lost in round-trip');
  }

  // scenario contract, exactly the shape the UI writes and reads back
  const scen = JSON.parse(JSON.stringify({
    schemaVersion: E.schemaVersion, kind: 'scenario', topology: 'buck',
    op: { Vin: 24, Vout: 12, Pout: 100, fsw: 75000 },
    A: 'IRF7759', B: 'EPC2361', N: 3, tj: 'none', cossBasis: 'VQoss',
  }));
  assert.equal(scen.kind, 'scenario');
  assert.equal(scen.schemaVersion, E.schemaVersion);
  const r = E.computeLosses(E.PARTS[scen.A],
    Object.assign(E.defaultOp(scen.topology), scen.op), scen.N, { tempMode: scen.tj });
  assert.ok(Number.isFinite(r.total) && r.total > 0, 'reloaded scenario must compute');
  assert.equal(E.TOPOLOGIES.includes(scen.topology), true);
});

/* ------------------------------------------------------------ bad input */
test('degenerate inputs do not produce NaN or negative losses', () => {
  const bad = [
    { topology: 'buck', Vin: 48, Vout: 12, Pout: 0, fsw: 100000, Tamb: 25, tauDead: 4e-8 },
    { topology: 'boost', Vin: 25, Vout: 55, Pout: 0, fsw: 0, Tamb: 25, tauDead: 4e-8 },
    { topology: 'threephase', Vdc: 58, Irms: 0, M: 0, PF: 0.9, fsw: 40000, Tamb: 25, tauDead: 4e-8 },
  ];
  for (const op of bad) {
    for (const pn of ['EPC2361', 'IRF7759']) {
      const r = E.computeLosses(E.PARTS[pn], op, 1, { tempMode: 'flat' });
      for (const k of TERMS) {
        assert.ok(Number.isFinite(r.terms[k]) && r.terms[k] >= -1e-12,
          JSON.stringify(op.topology) + '/' + pn + '.' + k + ' = ' + r.terms[k]);
      }
    }
  }
});

/* -------------------------------------------------- topology -> magnetics */
/* The design workspace has no free "load model" selector: the topology decides
   what the magnetics ARE.  These are structural assertions, not goldens,
   because they are about which model is selected rather than about a number. */
test('the topology decides what the inductance is and which core model applies', () => {
  const tp = E.profileFor('threephase', null);
  // 3-phase: the motor winding IS the inductance and the stator iron is the core.
  assert.equal(tp.inductance, 'winding');
  assert.equal(tp.core, 'iron');
  assert.equal(tp.machine, true);
  assert.equal(tp.ripple, 'svpwm');
  // Every DC-DC topology drives a discrete filter inductor and has no machine,
  // and reuses the ripple derive() already computes rather than a second model.
  for (const t of ['buck', 'boost', 'fourswitch']) {
    const p = E.profileFor(t, 'buck');
    assert.equal(p.inductance, 'filter', t + ' must use the filter inductor');
    assert.equal(p.core, 'inductor', t + ' must use the inductor core model');
    assert.equal(p.machine, false, t + ' has no machine');
    assert.equal(p.ripple, 'derive', t + ' must reuse the derive() ripple');
  }
  assert.equal(E.profileFor('nope', null), null, 'an unknown topology must resolve to null');
});

test('the capacitor node roles follow the topology, and the 4-switch mode picks the node', () => {
  // A node carrying the inductor ripple TRIANGLE takes the harmonic model; a
  // node carrying switched current takes the switching-function model.  Buck
  // and boost are mirror images: a different node is the smooth one.
  assert.deepEqual(E.profileFor('buck', null).caps, { out: 'smooth', in: 'pulsed' });
  assert.deepEqual(E.profileFor('boost', null).caps, { in: 'smooth', out: 'pulsed' });
  assert.deepEqual(E.profileFor('threephase', null).caps, { dclink: 'pulsed' });
  // The 4-switch converter is whichever of the two it is currently acting as, so
  // its node roles come from the mode derive() actually resolved -- which is what
  // stops the cap panel from contradicting the loss model in buck-boost mode.
  assert.equal(E.profileFor('fourswitch', 'buck').caps.out, 'smooth');
  assert.equal(E.profileFor('fourswitch', 'buck').caps.in, 'pulsed');
  assert.equal(E.profileFor('fourswitch', 'boost').caps.in, 'smooth');
  assert.equal(E.profileFor('fourswitch', 'boost').caps.out, 'pulsed');
  assert.equal(E.profileFor('fourswitch', 'buckboost').caps.in, 'pulsed');
  assert.equal(E.profileFor('fourswitch', 'buckboost').caps.out, 'pulsed');
  // The resolved mode is reported so the UI can say which one it took.
  assert.equal(E.profileFor('fourswitch', 'buck').resolvedMode, 'buck');
});

/* --------------------------------------------- 3-phase SVPWM ripple model */
/* svpwmRipple returns FLUX-domain quantities, which are independent of the
   inductance; only the current depends on Ls, by an exact 1/Ls.  That is what
   makes the required inductance one division rather than a solve, so these
   tests pin the flux quantities and the identities that follow from them. */
test('svpwmRipple matches the transcribed oracle', () => {
  const RIPPLE = G.ripple;
  assert.ok(RIPPLE && RIPPLE.length, 'golden.json carries no ripple section');
  for (const c of RIPPLE) {
    const r = E.svpwmRipple(c.vdc, c.M, c.fsw, c.nTheta, c.nSub);
    const where = 'ripple ' + c.vdc + 'V/M' + c.M + '/' + (c.fsw / 1e3) + 'k';
    assertClose(r.Vrms, c.expected.Vrms, where + '.Vrms');
    assertClose(r.lamRms, c.expected.lamRms, where + '.lamRms');
    assertClose(r.lamPPmax, c.expected.lamPPmax, where + '.lamPPmax');
    assertClose(r.fEff, c.expected.fEff, where + '.fEff');
    assertClose(r.lamPP, c.expected.lamPP, where + '.lamPP');
    assert.equal(r.Mclamped, c.expected.Mclamped, where + '.Mclamped');
    // Current-domain quantities and the sizing answer are exact divisions.
    assertClose(E.ripIrms(r, c.Ls), c.expected.Irip_rms, where + '.Irip_rms');
    assertClose(E.ripIpp(r, c.Ls), c.expected.Ipp, where + '.Ipp');
    assertClose(E.ripRequiredL(r, c.ipp_target), c.expected.requiredL, where + '.requiredL');
  }
});

test('svpwmRipple reproduces the exact SVPWM ripple closed forms', () => {
  // A golden from a transcription proves only that the port is faithful.  These
  // are the analytic anchors: the classic linear-region maximum
  // dI_pp,max = Vdc/(6*Ls*fsw) at M = 2/sqrt(3), and a second exact datum at
  // M = 1 where the same normalised constant is 1/(4*sqrt(3)).
  const ANCH = loadJSON('reference', 'external', 'ripple_anchors.json');
  assert.ok(ANCH.anchors.length >= 2, 'expected both analytic anchors');
  for (const a of ANCH.anchors) {
    const r = E.svpwmRipple(a.Vdc, a.M, a.fsw, 180, 192);
    const k = r.lamPPmax * a.fsw / a.Vdc;
    assertClose(k, a.k_expected, 'anchor ' + a.name, 1e-12, 1e-18);
  }
});

test('ripple flux is inductance-free and scales exactly with Vdc and 1/fsw', () => {
  const r = E.svpwmRipple(58, 1, 25000);
  // Only the current moves with Ls, and by exactly 1/Ls.
  for (const Ls of [1e-6, 3.73e-6, 7.16e-6, 100e-6]) {
    assertClose(E.ripIpp(r, Ls) / E.ripIpp(r, 2 * Ls), 2, 'Ipp ratio @' + Ls, 1e-12);
    assertClose(E.ripIrms(r, Ls) * Ls, r.lamRms, 'Irms*Ls @' + Ls, 1e-12);
  }
  // requiredL is the exact inverse of the ripple model, so the sizing panel and
  // the loss model cannot drift apart.
  for (const target of [5, 20, 46.8, 120]) {
    const L = E.ripRequiredL(r, target);
    assertClose(E.ripIpp(r, L), target, 'requiredL round-trip @' + target, 1e-12);
  }
  // Both are exact properties of the volt-second waveform.
  assertClose(E.svpwmRipple(116, 1, 25000).lamPPmax / r.lamPPmax, 2, 'Vdc scaling', 1e-12);
  assertClose(E.svpwmRipple(58, 1, 50000).lamPPmax / r.lamPPmax, 0.5, 'fsw scaling', 1e-12);
});

test('the sizing answer is resolution independent, the rms ripple voltage is not', () => {
  const res = loadJSON('reference', 'external', 'ripple_anchors.json').resolution;
  // lamPPmax is a peak-to-peak flux, so refining the grid cannot move it: the
  // required inductance is exact at any resolution setting.
  const lam = res.nSub.map(ns => E.svpwmRipple(58, 1, 25000, 180, ns).lamPPmax);
  const spread = (Math.max.apply(null, lam) - Math.min.apply(null, lam)) / Math.max.apply(null, lam);
  assert.ok(spread < 1e-12, 'lamPPmax moved with nSub: relative spread ' + spread);
  // Vrms is a mean square over binned pulse widths, so it does move, and it
  // converges upwards: the default 192 sits about 0.9% below the converged
  // value.  That is a documented property of the model, not a bug, and it is why
  // the iron ripple eddy term carries a note rather than a claim of exactness.
  const v = res.nSub.map(ns => E.svpwmRipple(58, 1, 25000, 180, ns).Vrms);
  assert.ok(v[v.length - 1] > v[0], 'Vrms must converge upwards');
  // Successive refinements must close the gap (monotone convergence), and the
  // coarsest-to-finest change must be far larger than the last one.
  for (let i = 1; i < v.length; i++) assert.ok(v[i] > v[i - 1], 'Vrms dipped at nSub ' + res.nSub[i]);
  const first = v[1] - v[0], last = v[v.length - 1] - v[v.length - 2];
  assert.ok(last < first / 4, 'the gap must shrink with refinement: ' + last + ' vs ' + first);
  assertClose(v[v.length - 1], res.Vrms_extrapolated, 'Vrms converged', 5e-3);
  const def = E.svpwmRipple(58, 1, 25000).Vrms;
  assert.ok(def < res.Vrms_extrapolated, 'the default must sit below the converged value');
});

test('svpwmRipple clamps at the linear limit and refuses degenerate inputs', () => {
  const Mmax = 2 / Math.sqrt(3);
  const over = E.svpwmRipple(58, 3.0, 25000);
  assert.equal(over.Mclamped, true, 'over-modulation must be flagged');
  assertClose(over.M, Mmax, 'clamped M', 1e-15);
  assertClose(over.lamPPmax, E.svpwmRipple(58, Mmax, 25000).lamPPmax, 'clamped ripple', 1e-12);
  // At M = 0 all three legs switch together, so the machine sees no differential
  // voltage and there is no ripple at all.
  const zero = E.svpwmRipple(58, 0, 25000);
  assert.equal(zero.lamPPmax, 0);
  assert.equal(zero.Vrms, 0);
  assert.equal(zero.fEff, 0);
  // The defaults are the resolution the committed MATLAB study uses.
  const d = E.svpwmRipple(58, 1, 25000);
  assert.equal(d.nTheta, 180);
  assert.equal(d.nSub, 192);
  // A zero bus or zero frequency has no meaning here: refuse, do not divide.
  assert.throws(() => E.svpwmRipple(0, 1, 25000), /Vdc/);
  assert.throws(() => E.svpwmRipple(58, 1, 0), /fsw/);
  assert.throws(() => E.svpwmRipple(58, 1, 25000, 0, 192), /nTheta/);
});

test('the reference point needs far more inductance than the winding provides', () => {
  // This is the sizing reality check the design workspace exists to show: at
  // 58 V, M = 1, 25 kHz, a 20% peak-to-peak ripple target needs ~7.2 uH at the
  // DeviceFOM.m reference current and ~14.8 uH at the live default 80 A rms.
  const r = E.svpwmRipple(58, 1, 25000);
  const L165 = E.ripRequiredL(r, 0.2 * Math.SQRT2 * 165.4);
  const L80 = E.ripRequiredL(r, 0.2 * Math.SQRT2 * 80);
  assert.ok(L165 > 7.0e-6 && L165 < 7.3e-6, 'L for 165.4 A rms was ' + L165);
  assert.ok(L80 > 14.5e-6 && L80 < 15.1e-6, 'L for 80 A rms was ' + L80);
  // The Lehner winding is 3.73 uH, so at 25 kHz the ripple is ~90 A pk-pk --
  // which is exactly why the committed study has to raise fsw, and why the
  // interior fsw optimum the comparator does not have is worth having.
  const ipp = E.ripIpp(r, 3.73e-6);
  assert.ok(ipp > 85 && ipp < 95, 'winding ripple was ' + ipp);
  assert.ok(E.ripIpp(E.svpwmRipple(58, 1, 60000), 3.73e-6) < ipp / 2,
    'doubling the carrier must more than halve the winding ripple');
});

/* ------------------------------------------------------ inductor library */
/* The seven seeded inductors are a transcription of the committed WE_*.m data,
   so these compare the embedded block back against the parsed anchor file --
   values, grid pairing and the log-log fit alike. */
test('the seeded inductor library matches the parsed WE data', () => {
  const A = loadJSON('reference', 'external', 'inductor_anchors.json');
  const pns = Object.keys(A.parts);
  assert.ok(pns.length >= 7, 'expected the seven committed WE parts');
  assert.equal(Object.keys(E.INDUCTORS).length, pns.length, 'library and anchors disagree on part count');

  // The axes are shared, and indGrid must pair every Pac value with its own
  // (f, dI, Idc) triple in the order the .m files list them.
  assert.deepEqual(E.MAGPARTS.indAxes.f, A.axes.f);
  assert.deepEqual(E.MAGPARTS.indAxes.dI, A.axes.dI);
  assert.deepEqual(E.MAGPARTS.indAxes.Idc, A.axes.Idc);
  assert.equal(E.MAGPARTS.indGrid.length, A.rows);
  const seen = new Set(E.MAGPARTS.indGrid.map(g => g.join('|')));
  assert.equal(seen.size, A.rows, 'indGrid repeats or drops a grid point');
  // A permutation claim needs every triple, not just the corners.
  for (const f of A.axes.f) for (const d of A.axes.dI) for (const i of A.axes.Idc)
    assert.ok(seen.has([f, d, i].join('|')), 'missing grid point ' + [f, d, i]);

  for (const pn of pns) {
    const a = A.parts[pn], p = E.INDUCTORS[pn];
    assert.ok(p, 'library is missing ' + pn);
    assertClose(p.L, a.L, pn + '.L');
    assertClose(p.DCR, a.DCR, pn + '.DCR');
    assertClose(p.Isat10, a.Isat10, pn + '.Isat10');
    assertClose(p.Isat30, a.Isat30, pn + '.Isat30');
    assertClose(p.Irated, a.Irated, pn + '.Irated');
    assertClose(p.Pac, a.Pac, pn + '.Pac');
    // Everything here is a datasheet or REDEXPERT number, so nothing is guessed.
    assert.deepEqual(p.est, [], pn + ' should carry no estimate fields');
  }
});

test('the inductor loss fit matches the independent anchor fit', () => {
  const A = loadJSON('reference', 'external', 'inductor_anchors.json');
  for (const pn of Object.keys(A.parts)) {
    const f = E.fitInductorLoss(E.INDUCTORS[pn]), e = A.parts[pn].fit;
    assertClose(f.k, e.k, pn + '.k', 1e-9);
    assertClose(f.a, e.a, pn + '.a', 1e-9);
    assertClose(f.b, e.b, pn + '.b', 1e-9);
    assertClose(f.c, e.c, pn + '.c', 1e-9);
    assertClose(f.residMax, e.residMax, pn + '.residMax', 1e-6);
    assert.equal(f.rows, A.rows, pn + '.rows');
    assert.ok(f.condEst < 1e4, pn + ' condEst ' + f.condEst);
  }
  // The two parts the committed .m files document as saturating.  Matching
  // their documented bias exponents is what proves the grid axes are paired
  // f/dI/Idc and not, say, dI/Idc swapped -- which a cross-port test cannot
  // catch, because both ports would make the same swap.
  const sat = E.inductorFit(E.INDUCTORS.WE_7443634700);
  assert.ok(sat.c < -3.7 && sat.c > -3.9, 'WE_7443634700 bias exponent was ' + sat.c);
  assert.ok(sat.residMax > 0.25, 'WE_7443634700 residual was ' + sat.residMax);
  const ok = E.inductorFit(E.INDUCTORS.WE_7443642200);
  assert.ok(Math.abs(ok.c) < 0.1, 'WE_7443642200 bias exponent was ' + ok.c);
});

test('inductorAcLoss is the fitted power law and interpolates its own grid', () => {
  const A = loadJSON('reference', 'external', 'inductor_anchors.json');
  const pn = 'WE_7443641500', p = E.INDUCTORS[pn], F = E.inductorFit(p);
  const f = 2e5, dI = 3, Idc = 10;
  const base = E.inductorAcLoss(p, f, dI, Idc);
  assertClose(base, F.k * Math.pow(f, F.a) * Math.pow(dI, F.b) * Math.pow(Idc, F.c), 'power law', 1e-12);
  assertClose(E.inductorAcLoss(p, 2 * f, dI, Idc) / base, Math.pow(2, F.a), 'frequency exponent', 1e-12);
  assertClose(E.inductorAcLoss(p, f, 2 * dI, Idc) / base, Math.pow(2, F.b), 'ripple exponent', 1e-12);
  assertClose(E.inductorAcLoss(p, f, dI, 2 * Idc) / base, Math.pow(2, F.c), 'bias exponent', 1e-12);
  // No ripple or no switching means no AC loss, not a NaN.
  assert.equal(E.inductorAcLoss(p, f, 0, Idc), 0);
  assert.equal(E.inductorAcLoss(p, 0, dI, Idc), 0);
  assert.equal(E.inductorAcLoss(p, f, dI, 0), 0);
  // On its own grid the fit must stay inside the residual it reports.
  const g = E.MAGPARTS.indGrid, pac = A.parts[pn].Pac;
  for (let i = 0; i < g.length; i++) {
    const pred = E.inductorAcLoss(p, g[i][0], g[i][1], g[i][2]);
    assert.ok(Math.abs(pred / pac[i] - 1) <= F.residMax + 1e-12,
      'grid row ' + i + ' is outside the reported residual');
  }
  // The DC side is I^2 R, the port of boostBridgeLoss.m's P.Lesr.
  assertClose(E.inductorDcLoss(p, 12), p.DCR * 144, 'I^2 R', 1e-15);
  assert.equal(E.inductorDcLoss(p, 0), 0);
});

test('the inductor fit refuses a grid that cannot identify its exponents', () => {
  // The old data files swept f and dI along ONE converter curve, so log(dI) was
  // an affine function of log(f), the design matrix went rank deficient, and
  // the solver returned b = -0.215 -- "more ripple, less core loss".  This
  // reproduces exactly that shape and demands a refusal rather than a number.
  const g = E.MAGPARTS.indGrid, badGrid = [], badPac = [];
  for (let i = 0; i < g.length; i++) {
    const f = g[i][0], Idc = g[i][2];
    const dI = 1e-9 * Math.pow(f, 0.5);                  // dI tied to f
    badGrid.push([f, dI, Idc]);
    badPac.push(1e-12 * Math.pow(f, 0.8) * Math.pow(dI, 2) * Math.pow(Idc, 0.1));
  }
  const part = { PN: 'DEGENERATE', grid: badGrid, Pac: badPac, L: 1e-5, DCR: 1e-3 };
  assert.throws(() => E.fitInductorLoss(part), /rank deficient|ill-conditioned/);
});

test('a custom inductor carries its own exponents instead of a grid', () => {
  const c = { PN: 'CUSTOM', L: 20e-6, DCR: 1e-3, kAc: 2e-5, aAc: 0.7, bAc: 2.0, cAc: -0.05 };
  assert.equal(E.inductorFit(c).source, 'custom');
  assertClose(E.inductorFit(c).k, 2e-5, 'custom k');
  assertClose(E.inductorAcLoss(c, 100e3, 2, 10),
    2e-5 * Math.pow(1e5, 0.7) * Math.pow(2, 2) * Math.pow(10, -0.05), 'custom loss', 1e-12);
  assert.throws(() => E.inductorFit({ PN: 'NOPE' }), /loss grid|k\/a\/b\/c/);
});

test('the DC-DC required inductance round-trips through the loss model', () => {
  const D = G.dcdc;
  assert.ok(D && D.length >= 6, 'golden.json carries no dcdc section');
  for (const r of D) {
    const op = Object.assign(E.defaultOp(r.topology), r.op);
    const where = r.topology + ' Vin=' + r.op.Vin + ' Vout=' + r.op.Vout + ' @' + (r.op.fsw / 1e3) + 'k';
    const L = E.dcRequiredL(op, r.topology, r.ipp_target);
    assertClose(L, r.expected.requiredL, where + '.requiredL');
    // The check that matters: put the answer back into the model the losses are
    // built on and demand the exact ripple target.  Two ports sharing a
    // transcription error cannot satisfy this.
    const d = E.derive(Object.assign({}, op, { L: L }), r.topology);
    assertClose(d.dIL, r.ipp_target, where + '.dIL round-trip', 1e-12);
    assert.equal(d.mode, r.expected.mode_at_required, where + '.mode');
  }
  // 3-phase ripple belongs to the winding, not a filter inductor: refuse
  // rather than silently answering with a DC-DC formula.
  assert.throws(() => E.dcRequiredL(E.defaultOp('threephase'), 'threephase', 20), /winding/);
  assert.throws(() => E.dcRequiredL(Object.assign(E.defaultOp('buck'), { fsw: 0 }), 'buck', 2), /fsw/);
  assert.throws(() => E.dcRequiredL(E.defaultOp('buck'), 'buck', 0), /target/);
});

test('no seeded inductor can carry the reference-phase current', () => {
  // A statement about the committed data, not about the model: the seven parts
  // saturate between 7.5 A and 27 A, and the tool's own reference point peaks
  // at 234 A.  The design workspace must say so rather than flatter a part.
  const ipk = Math.SQRT2 * 165.4;
  for (const pn of Object.keys(E.INDUCTORS)) {
    const p = E.INDUCTORS[pn];
    assert.ok(p.Isat30 != null && p.Isat30 < ipk, pn + ' claims to carry ' + ipk + ' A');
  }
  const big = Object.keys(E.INDUCTORS).filter(pn => E.INDUCTORS[pn].Isat30 > 100);
  assert.equal(big.length, 0, 'none of the committed parts is a 100 A+ inductor');
  // ...which is why the custom-inductor path has to exist.
  const r = E.svpwmRipple(58, 1, 25000);
  const need = E.ripRequiredL(r, 0.2 * Math.SQRT2 * 165.4);
  assert.ok(need > 7e-6, 'and the sizing answer is ' + (need * 1e6).toFixed(1) + ' uH');
});

/* --------------------------------------------------------- capacitor model */
test('capBank collapses series and parallel strings', () => {
  const b = E.capBank({ C: 100e-6, ESR: 10e-3, nSeries: 2, nParallel: 4, PN: 'x' });
  assertClose(b.C, 100e-6 * 4 / 2, 'C');
  assertClose(b.ESR, 10e-3 * 2 / 4, 'ESR');
  const d = E.capBank({ C: 10e-6, ESR: 1e-3 });
  assert.equal(d.nSeries, 1);
  assert.equal(d.nParallel, 1);
  assertClose(d.C, 10e-6, 'default C');
  assertClose(d.ESR, 1e-3, 'default ESR');
});

test('a pulsed capacitor node matches the textbook CCM closed form', () => {
  const A = loadJSON('reference', 'external', 'cap_anchors.json');
  assert.ok(A.pulsed.length >= 4, 'expected the closed-form anchor cases');
  for (const c of A.pulsed) {
    const topo = c.name.startsWith('buck') ? 'buck' : 'boost';
    const op = Object.assign(E.defaultOp(topo), { Vin: c.Vin, Vout: c.Vout, Pout: c.Pout, fsw: c.fsw });
    const node = E.capNodes(op, topo, topo).find(n => n.node === c.node);
    assert.ok(node, c.name + ': no ' + c.node + ' node');
    assert.equal(node.kind, 'pulsed', c.name + ' must be the pulsed node');
    const r = E.capNodeResult(node, E.capBank({ C: c.C, ESR: 0, PN: 'anchor' }), c.fsw);
    assertClose(r.Irms, c.expected.Irms, c.name + '.Irms', 1e-12);
    assertClose(r.dvCap, c.expected.dvCap, c.name + '.dvCap', 1e-12);
    // ESR is a pure step on top of the charge ramp, not a second ramp.
    const e = E.capNodeResult(node, E.capBank({ C: c.C, ESR: 1e-3, PN: 'anchor' }), c.fsw);
    assertClose(e.dvpp, r.dvCap + Math.abs(node.Ihi - node.Ilo) * 1e-3, c.name + '.dvpp', 1e-12);
  }
});

test('the smooth-node harmonic sum satisfies Parseval, correcting a 4x .m error', () => {
  const A = loadJSON('reference', 'external', 'cap_anchors.json');
  const dIL = A.parseval.dIL;
  // One bank, so no current division can lose amplitude.
  const bank = () => [E.capBank({ C: 1e-3, ESR: 1e-12, PN: 'one' })];
  const sumOf = out => out.reduce((a, b) => a + b.Irms2, 0);
  const total = A.parseval.expected_sum_mean_square;
  const sum = sumOf(E.smoothCapLoss(bank(), dIL, 1e5, 15));
  // A truncated harmonic sum must UNDERSHOOT Parseval, and the shortfall must
  // be a tail rather than a wrong amplitude: the odd-harmonic tail past N is
  // bounded by (8*dI^2/pi^4) * 1/(3N^3).
  const N = 2 * 15 - 1;
  const tail = 8 * dIL * dIL / Math.pow(Math.PI, 4) * (1 / (3 * Math.pow(N, 3)));
  assert.ok(sum < total, 'the truncated sum must undershoot Parseval');
  assert.ok(total - sum < tail, 'deficit ' + (total - sum) + ' exceeds the tail bound ' + tail);
  // Refining closes the gap, and then the rms is the triangle's own closed form
  // dI/sqrt(12): the harmonic model and the closed form agree.
  const sum2 = sumOf(E.smoothCapLoss(bank(), dIL, 1e5, 400));
  assert.ok(sum2 > sum, 'more harmonics must add power');
  assert.ok(Math.abs(sum2 - total) < Math.abs(sum - total) / 100, 'the gap must close rapidly');
  assertClose(Math.sqrt(sum2), dIL / Math.sqrt(12), 'triangle rms', 1e-9);
  // Capacitor_Losses.m uses 8*dI/(pi^2*n^2) while defining dI as peak-to-peak;
  // the peak-to-peak definition gives 4*dI/(pi^2*n^2), i.e. half the amplitude
  // and a quarter of the ESR loss.  This port uses the latter; pin both so the
  // divergence stays visible rather than being quietly "fixed".
  assertClose(E.triHarmPeak(dIL, 1), 4 * dIL / Math.pow(Math.PI, 2), 'first harmonic peak', 1e-15);
  assertClose(E.triHarmPeak(dIL, 1) / (8 * dIL / Math.pow(Math.PI, 2)), 0.5, 'the .m amplitude ratio', 1e-15);
  // Smooth node anchors.
  const s = A.smooth;
  const r = E.capNodeResult({ node: 'out', kind: 'smooth', dIL: s.dIL },
    E.capBank({ C: s.C, ESR: 0, PN: 'x' }), s.fsw);
  assertClose(r.Irms, s.expected.Irms, 'smooth Irms', 1e-12);
  assertClose(r.dvCap, s.expected.dvCap, 'smooth dvCap', 1e-12);
});

test('requiredC hits its voltage target, and an ESR-bound node is flagged', () => {
  const A = loadJSON('reference', 'external', 'cap_anchors.json');
  for (const c of A.pulsed) {
    const topo = c.name.startsWith('buck') ? 'buck' : 'boost';
    const op = Object.assign(E.defaultOp(topo), { Vin: c.Vin, Vout: c.Vout, Pout: c.Pout, fsw: c.fsw });
    const node = E.capNodes(op, topo, topo).find(n => n.node === c.node);
    const bank = E.capBank({ C: c.C, ESR: 2e-3, PN: 'x' });
    const req = E.capRequired(node, bank, 0.5, c.fsw);
    assert.equal(req.esrBound, false, c.name + ' should be reachable at 0.5 V');
    // With that capacitance the model must land exactly on the target.
    const r = E.capNodeResult(node, E.capBank({ C: req.Creq, ESR: 0, PN: 'x' }), c.fsw);
    assertClose(r.dvCap, 0.5 - req.esrStep, c.name + '.dvCap', 1e-12);
    // A target below the ESR step cannot be met by any capacitance.
    const tight = E.capRequired(node, bank, req.esrStep * 0.5, c.fsw);
    assert.equal(tight.Creq, null, c.name + ' must refuse rather than go negative');
    assert.equal(tight.esrBound, true);
  }
  const s = A.smooth;
  const node = { node: 'out', kind: 'smooth', dIL: s.dIL };
  const bank = E.capBank({ C: s.C, ESR: 1e-3, PN: 'x' });
  const req = E.capRequired(node, bank, 1.0, s.fsw);
  assert.equal(req.esrBound, false);
  assertClose(E.capNodeResult(node, E.capBank({ C: req.Creq, ESR: 0, PN: 'x' }), s.fsw).dvCap,
    1.0 - req.esrStep, 'smooth dvCap', 1e-12);
});

test('capacitor nodes follow the topology profile and the resolved mode', () => {
  const kindOf = (nodes, n) => nodes.find(x => x.node === n).kind;
  const buck = E.capNodes(Object.assign(E.defaultOp('buck'), { Vin: 48, Vout: 12, Pout: 240, fsw: 1e5 }), 'buck', 'buck');
  assert.equal(kindOf(buck, 'in'), 'pulsed');
  assert.equal(kindOf(buck, 'out'), 'smooth');
  const boost = E.capNodes(Object.assign(E.defaultOp('boost'), { Vin: 25, Vout: 55, Pout: 110, fsw: 2e5 }), 'boost', 'boost');
  assert.equal(kindOf(boost, 'in'), 'smooth');
  assert.equal(kindOf(boost, 'out'), 'pulsed');
  // 4-switch: the resolved mode picks which node is the smooth one, and
  // buck-boost leaves neither smooth -- which is what the profile table says.
  const op4 = Object.assign(E.defaultOp('fourswitch'), { Vin: 48, Vout: 12, Pout: 240, fsw: 1e5 });
  assert.equal(kindOf(E.capNodes(op4, 'fourswitch', 'buck'), 'out'), 'smooth');
  assert.equal(kindOf(E.capNodes(op4, 'fourswitch', 'boost'), 'in'), 'smooth');
  for (const n of E.capNodes(op4, 'fourswitch', 'buckboost')) assert.equal(n.kind, 'pulsed');
  // 3-phase has the DC link, which is neither DC-DC node kind: it needs the
  // switching-function model, and this function says so rather than guessing.
  const tp = E.capNodes(E.defaultOp('threephase'), 'threephase', null);
  assert.equal(tp.length, 1);
  assert.equal(tp[0].node, 'dclink');
  assert.equal(tp[0].kind, 'pulsed-svpwm');
  assert.equal(E.capNodeResult(tp[0], E.capBank({ C: 1e-3, ESR: 1e-3 }), 25000), null);
  assert.throws(() => E.capNodes(E.defaultOp('buck'), 'nope', null), /unknown topology/);
});

test('every seeded capacitor is badged generic, because no datasheet is committed', () => {
  const pns = Object.keys(E.CAPS);
  assert.ok(pns.length >= 4, 'expected the four generic examples');
  for (const pn of pns) {
    const c = E.CAPS[pn];
    assert.ok(c.est.includes('ESR') && c.est.includes('C'), pn + ' must badge C and ESR as estimates');
    assert.match(c.notes, /Generic/, pn + ' must say it is generic');
    assert.ok(c.C > 0 && c.ESR > 0, pn + ' needs a positive C and ESR');
  }
});

/* ------------------------------------------------------------ machine model */
test('the seeded machine derives the parameters the committed study documents', () => {
  const A = loadJSON('reference', 'external', 'machine_anchors.json');
  const mot = E.MOTORS.LEHNER_7050_10, m = E.motorDerive(mot), d = A.derived;
  assertClose(m.Rcable, d.Rcable, 'Rcable', 1e-12);
  assertClose(m.Rwind, d.Rwind, 'Rwind', 1e-12);
  assertClose(m.cabDia, d.cabDia, 'cabDia', 1e-12);
  assertClose(m.KtPk, d.KtPk, 'KtPk', 1e-12);
  assertClose(m.Kh, d.Kh, 'Kh', 1e-9);
  assertClose(m.Ke, d.Ke, 'Ke', 1e-9);
  assertClose(m.alphaEquiv, d.alphaEquiv, 'alphaEquiv', 1e-9);
  assertClose(m.ironSplit, d.ironSplit, 'ironSplit', 1e-9);
  // The .m file's own sanity statement: 9.1 mOhm splits into roughly 5.8 mOhm
  // of winding, 2.2 mOhm of cable and 1.2 mOhm of connectors and busbar, and
  // that winding value is what reproduces Lehner's 92-93% motor efficiency.
  assert.ok(Math.abs(m.Rwind - 5.8e-3) < 0.15e-3, 'Rwind ' + m.Rwind);
  assert.ok(Math.abs(m.Rcable - 2.15e-3) < 0.1e-3, 'Rcable ' + m.Rcable);
  assertClose(m.Rwind + m.Rcable + m.Rfix, m.Rph, 'the split must sum to Rph', 1e-12);
  // Hysteresis is about a third of the iron loss at the calibration frequency.
  assert.ok(m.ironSplit[0] > 0.30 && m.ironSplit[0] < 0.36, 'hysteresis share ' + m.ironSplit[0]);
});

test('the iron calibration reproduces both no-load dyno rows', () => {
  const A = loadJSON('reference', 'external', 'machine_anchors.json');
  assert.equal(A.cal.length, 2, 'expected the two dyno rows');
  for (const c of A.cal) {
    // No load, no PWM: the current is zero and there is no ripple, so only the
    // fundamental iron terms survive -- exactly what the calibration solved for.
    const r = E.motorLosses(E.MOTORS.LEHNER_7050_10,
      { Irms: 0, f1: c.f, we: 2 * Math.PI * c.f }, null, 0);
    assertClose(r.ironFund, c.model, c.name + '.ironFund', 1e-9);
    assert.ok(Math.abs(r.ironFund / c.dyno - 1) < 1e-3,
      c.name + ' is ' + ((r.ironFund / c.dyno - 1) * 100).toFixed(3) + '% off its dyno row');
    assertClose(r.FeF, c.lamEddyFactor, c.name + '.lamEddyFactor', 1e-9);
  }
});

test('the AC-resistance and lamination factors match their analytic limits', () => {
  const A = loadJSON('reference', 'external', 'machine_anchors.json');
  const f = A.factors, d = E.motorDerive(E.MOTORS.LEHNER_7050_10).cabDia;
  // Skin effect: exactly 1 in the dc limit, and a/(2*delta) + 1/4 once the
  // skin depth is small.  That +1/4 is the classic asymptotic term, so it is a
  // real check of the Bessel evaluation rather than of the series it came from.
  assert.ok(Math.abs(E.skinFr(1e-6, d) - 1) < 1e-6, 'skinFr must tend to 1 at dc, got ' + E.skinFr(1e-6, d));
  assert.ok(Math.abs(E.dowellFr(1e-6, 1e-3, 4, 0.8) - 1) < 1e-6,
    'dowellFr must tend to 1 at dc, got ' + E.dowellFr(1e-6, 1e-3, 4, 0.8));
  for (const s of f.skin) {
    assertClose(E.skinFr(s.f, d), s.Fr, 'skinFr(' + s.f + ' Hz)', 1e-9);
    if (s.f >= 40000) {
      assert.ok(Math.abs(s.difference - 0.25) < 0.02,
        'skinFr at ' + s.f + ' Hz should approach a/(2*delta)+1/4, off by ' + s.difference);
    }
  }
  // Proximity effect: 1 at dc, and layer count is what makes it dominate.
  assertClose(E.dowellFr(60000, 1e-3, 4, 0.8), f.dowellFr_60k, 'dowellFr 60 kHz', 1e-9);
  assert.ok(E.dowellFr(60000, 1e-3, 4, 0.8) > 10 * E.dowellFr(60000, 1e-3, 1, 0.8),
    'four layers must dominate a skin-only winding');
  // Lamination eddy factor: 1 for slow flux, and xi*F -> 3 when skin-limited,
  // which is the only way raising fsw reduces the ripple eddy loss.
  assertClose(E.lamEddyFactor(1e-9, 0.2e-3, 0.5e-6, 500), 1, 'lamEddyFactor small xi', 1e-9);
  assertClose(f.lamEddyFactor_xi_times_F, 3, 'xi*F limit', 1e-6);
});

test('motorLosses splits winding from harness and follows the AC factors', () => {
  const mot = E.MOTORS.LEHNER_7050_10, m = E.motorDerive(mot);
  const f1 = 60000;                       // where the AC factors actually bite
  const r = E.motorLosses(mot, { Irms: 100, f1: f1, we: 2 * Math.PI * f1 }, null, 0);
  const FrF = E.dowellFr(f1, m.dStrand, m.mLayers, m.poros), ScF = E.skinFr(f1, m.cabDia);
  assertClose(r.cuFundW, 3 * m.Rwind * FrF * 100 * 100, 'cuFundW', 1e-12);
  assertClose(r.cuFundH, 3 * (m.Rcable * ScF + m.Rfix) * 100 * 100, 'cuFundH', 1e-12);
  assertClose(r.cuFund, r.cuFundW + r.cuFundH, 'cuFund', 1e-12);
  // No ripple, no ripple loss -- and the DC part is untouched by it.
  assert.equal(r.cuRip, 0);
  assert.equal(r.ironRip, 0);
  // The slot winding takes the proximity factor and the cable does not, which is
  // the entire reason the .m file splits Rph three ways.  That file quotes
  // "Fr ~ 30" for the winding at 60 kHz against "2-3" for the cable; for this
  // 4.5 mm equivalent cable the port gives 34.8 against 4.4, so the winding
  // still pays far more but the cable figure is larger than that note implies.
  assert.ok(r.FrF / r.ScF > 5, 'Dowell proximity must dominate cable skin effect: ' + (r.FrF / r.ScF));
  assert.ok(r.FrF > 30, 'four layers at 60 kHz should give Fr around 35, got ' + r.FrF);
  assert.ok(r.cuFund > 3 * m.Rph * 100 * 100, 'AC factors must add loss, not remove it');
  assertClose(r.total, r.cuFund + r.ironFund, 'total with no ripple', 1e-12);
});

test('the machine ripple terms follow the PWM ripple', () => {
  const mot = E.MOTORS.LEHNER_7050_10;
  const rip = E.svpwmRipple(58, 1, 25000);
  const eop = { Irms: 80, f1: 300, we: 2 * Math.PI * 300, Ls: 3.73e-6, fsw: 25000 };
  const r = E.motorLosses(mot, eop, rip, 25000);
  assertClose(r.Irip, rip.lamRms / 3.73e-6, 'Irip', 1e-12);
  assert.ok(r.cuRip > 0 && r.ironRip > 0, 'ripple must drive both copper and iron loss');
  const r2 = E.motorLosses(mot, Object.assign({}, eop, { Ls: 7.46e-6 }), rip, 25000);
  // Ripple copper is 3*Rac*Irip^2 with Irip = lamRms/Ls, so doubling Ls quarters it.
  assertClose(r2.cuRipW / r.cuRipW, 0.25, 'ripple copper falls as 1/Ls^2', 1e-9);
  assertClose(r2.cuRipH / r.cuRipH, 0.25, 'harness ripple copper falls as 1/Ls^2', 1e-9);
  // The IRON ripple terms do NOT move with the inductance: the flux swing is set
  // by the applied volt-seconds, which are L-free, so both the hysteresis minor
  // loop and the eddy term are unchanged when the current ripple changes.  Only
  // the copper follows the current.  This is what motorDriveLoss.m computes and
  // it is the reason adding inductance is not a free win for iron loss.
  assertClose(r2.ironRipHyst, r.ironRipHyst, 'hysteresis ripple loss is L-independent', 1e-12);
  assertClose(r2.ironRipEddy, r.ironRipEddy, 'eddy ripple loss is L-independent', 1e-12);
  // A higher carrier cuts the ripple current and therefore its copper loss, and
  // cuts the hysteresis minor loop because there are fewer volt-seconds per cycle.
  const r3 = E.motorLosses(mot, Object.assign({}, eop, { fsw: 50000 }), E.svpwmRipple(58, 1, 50000), 50000);
  assert.ok(r3.cuRip < r.cuRip, 'a higher carrier must cut ripple copper');
  assert.ok(r3.ironRipHyst < r.ironRipHyst, 'a higher carrier must cut the hysteresis minor loop');
});

test('lehnerOpPoint inverts torque and speed the way the committed model does', () => {
  const mot = E.MOTORS.LEHNER_7050_10, m = E.motorDerive(mot);
  const o = E.lehnerOpPoint(mot, 58, 8000, 5.0);
  assertClose(o.Ipk, 5.0 / m.KtPk, 'Ipk', 1e-12);
  assertClose(o.Irms, o.Ipk / Math.SQRT2, 'Irms', 1e-12);
  assertClose(o.f1, 8000 / 60 * mot.p, 'f1', 1e-12);
  assertClose(o.we, 2 * Math.PI * o.f1, 'we', 1e-12);
  assertClose(o.Pout, 5.0 * 8000 / 60 * 2 * Math.PI, 'Pout', 1e-12);
  // M is the modulation needed to HOLD the point at id = 0, from the .m file's
  // (vq, vd) pair -- an output, not an input.
  const vq = m.Rph * o.Ipk + m.lam * o.we, vd = -o.we * m.Ls * o.Ipk;
  assertClose(o.M, Math.hypot(vd, vq) / 29, 'M', 1e-12);
  assert.equal(o.satM, o.M > 2 / Math.sqrt(3), 'satM must track M');
  assert.equal(E.lehnerOpPoint(mot, 58, 2000, 5).satM, false, 'low speed is inside the linear limit');
  assert.equal(E.lehnerOpPoint(mot, 58, 19000, 20).satM, true, 'high speed must flag over-modulation');
});

test('the seeded machine badges every estimated field', () => {
  const mot = E.MOTORS.LEHNER_7050_10;
  for (const k of ['Ls', 'fracIron', 'beta', 'kLm', 'dLam', 'rhoLam', 'muRLam',
                   'dStrand', 'mLayers', 'poros', 'cabLen', 'cabArea', 'Rfix'])
    assert.ok(mot.est.includes(k), k + ' is an estimate and must be badged');
  // lambda and Rph are MEASURED, so badging them would understate the data.
  for (const k of ['lam', 'Rph'])
    assert.ok(!mot.est.includes(k), k + ' is measured, not estimated');
  assert.match(mot.notes, /MEASURED/);
  assert.match(mot.notes, /ESTIMATED/);
});

/* ------------------------------------------------- REDEXPERT bias + thermal */
/* The bias curve and the thermal grid are scraped from Wuerth REDEXPERT, so
   these compare the baked table back against the parsed anchor file, then test
   the model built on it. */
test('the embedded bias and thermal table matches the scraped anchors', () => {
  const A = loadJSON('reference', 'external', 'bias_anchors.json');
  const pns = Object.keys(A.parts);
  assert.ok(pns.length >= 7, 'expected the seven seeded parts');
  for (const pn of pns) {
    const a = A.parts[pn], s = E.MAGPARTS.sat[pn];
    assert.ok(s, 'no SAT entry for ' + pn);
    assertClose(s.I, a.curve.map(r => r.I), pn + '.I');
    assertClose(s.L, a.curve.map(r => r.Leff), pn + '.L');
    assertClose(s.IvalidMax, a.IvalidMax, pn + '.IvalidMax');
    assertClose(s.LeffMin, a.LeffMin, pn + '.LeffMin');
    // The thermal grid must be rectangular, because the engine interpolates it
    // bilinearly and needs all four corners of the bracketing cell.
    const Is = [...new Set(s.th.map(t => t[0]))].length;
    const Ds = [...new Set(s.th.map(t => t[1]))].length;
    assert.equal(s.th.length, Is * Ds, pn + ': thermal grid is not rectangular');
    for (const t of a.thermal) {
      if (t.dT == null) continue;
      const hit = s.th.find(x => x[0] === t.I && x[1] === t.dI);
      assert.ok(hit, pn + ': missing thermal point ' + t.I + '/' + t.dI);
      // The generator rounds dT to one decimal; Python and JS disagree on
      // exact halves, so allow one rounding step.
      assertClose(hit[2], t.dT, pn + ' dT @' + t.I + '/' + t.dI, 1e-12, 0.051);
    }
  }
});

test('the bias curve is monotone and stops where the vendor model does', () => {
  const A = loadJSON('reference', 'external', 'bias_anchors.json');
  let rejected = 0;
  for (const pn of Object.keys(A.parts)) {
    const rec = A.parts[pn], c = rec.curve;
    // A saturating core never GAINS inductance with bias.  That is what makes
    // the scrape self-checking: REDEXPERT's bail-out shows up as L_eff snapping
    // back to the nominal value, which would break monotonicity -- so the curve
    // is truncated before it rather than recording a flattering answer.
    for (let i = 1; i < c.length; i++)
      assert.ok(c[i].Leff <= c[i - 1].Leff + 1e-12,
        pn + ': L_eff rose from ' + c[i - 1].Leff + ' to ' + c[i].Leff + ' at I=' + c[i].I);
    // The low-bias point must be the nominal inductance, or the excitation or the
    // field mapping is wrong.
    assert.ok(rec.lowBiasRatio > 0.95 && rec.lowBiasRatio < 1.05,
      pn + ': low-bias L_eff/L_nom = ' + rec.lowBiasRatio);
    // The curve ends exactly at the last point the vendor model covered.
    assertClose(c[c.length - 1].I, rec.IvalidMax, pn + '.IvalidMax');
    for (const r of rec.rejected) {
      rejected++;
      if (r.Leff != null)
        assert.ok(r.Leff > c[c.length - 1].Leff * 1.05,
          pn + ': a rejected point should show the model reverting, got ' + r.Leff);
    }
  }
  assert.ok(rejected >= 1, 'expected at least one bailed-out point in the scraped data');
});

test('satInductance interpolates the curve and flags bias past the model', () => {
  const p = E.INDUCTORS.WE_7443634700, s = E.MAGPARTS.sat.WE_7443634700;
  for (let i = 0; i < s.I.length; i++)
    assertClose(E.satInductance(p, s.I[i]).L, s.L[i], 'node ' + i, 1e-12);
  const mid = (s.I[3] + s.I[4]) / 2, got = E.satInductance(p, mid).L;
  assert.ok(got < s.L[3] && got > s.L[4], 'between nodes it must interpolate, got ' + got);
  assertClose(E.satInductance(p, 0.1).L, s.L[0], 'below the first point', 1e-12);
  assert.equal(E.satInductance(p, 0.1).below, true);
  // Past the last modelled point the inductance is UNKNOWN, not nominal.
  const over = E.satInductance(p, s.IvalidMax * 2);
  assert.equal(over.beyond, true);
  assertClose(over.L, s.L[s.L.length - 1], 'past the end it clamps to its last point', 1e-12);
  assert.equal(E.satInductance({ PN: 'NOPE', L: 1e-5 }, 5), null);
  assert.equal(E.satCurve({ PN: 'NOPE' }), null);
});

test('inductorRise interpolates the thermal grid and refuses to extrapolate', () => {
  const p = E.INDUCTORS.WE_74437636351012, s = E.MAGPARTS.sat.WE_74437636351012;
  const n = s.th[0];
  assertClose(E.inductorRise(p, n[0], n[1]), n[2], 'a grid node', 1e-12);
  const Is = s.th.map(t => t[0]), Ds = s.th.map(t => t[1]);
  const im = (Math.min.apply(null, Is) + Math.max.apply(null, Is)) / 2;
  const dm = (Math.min.apply(null, Ds) + Math.max.apply(null, Ds)) / 2;
  const mid = E.inductorRise(p, im, dm);
  assert.ok(mid > 0 && isFinite(mid), 'mid-grid rise was ' + mid);
  // Outside the grid: null, not a trend.
  assert.equal(E.inductorRise(p, Math.max.apply(null, Is) * 3, n[1]), null);
  assert.equal(E.inductorRise(p, n[0], Math.max.apply(null, Ds) * 3), null);
  assert.equal(E.inductorRise({ PN: 'NOPE' }, 5, 1), null);
});

test('the bias fixed point grows the ripple as the core rolls off', () => {
  const p = E.INDUCTORS.WE_7443634700;                      // rolls off hard
  const mk = (pout, fsw) => Object.assign(E.defaultOp('buck'),
    { Vin: 48, Vout: 12, Pout: pout, fsw: fsw });
  // DEEP bias at a low carrier: the ripple is large, so the peak runs well past
  // Isat, the core rolls off, and the ripple then grows further.
  const deep = mk(120, 2e4);
  const low = E.stageSystem({ A: 'EPC2361', NA: 2, ind: p }, deep, {});
  assert.ok(low.sat, 'saturation must be solved');
  const nominalIpp = 12 * (1 - 12 / 48) / (p.L * 2e4);
  assert.ok(low.sat.ipp > nominalIpp * 1.5,
    'roll-off must grow the ripple: got ' + low.sat.ipp + ' vs nominal ' + nominalIpp);
  assert.ok(low.sat.Leff < 0.9 * p.L, 'and the effective inductance must fall: ' + low.sat.Leff);
  // The reported ripple IS the saturated one: it must equal derive() at the
  // effective inductance, i.e. the whole pipeline saw the same number.
  const d2 = E.derive(Object.assign({}, deep, { L: low.sat.Leff }), 'buck');
  assertClose(low.dILind, d2.dIL, 'reported ripple vs effective-L ripple', 1e-9);
  assertClose(low.ipp, low.dILind, 'out.ipp must be the inductor ripple', 1e-12);
  // SHALLOW bias at a high carrier: Idc is 3 A, so even a doubled peak sits on
  // the flat part of the curve and the inductance is essentially nominal.  Note
  // that a high carrier alone is NOT enough -- with a 10 A bias this 8.5 A part
  // is already rolled off whatever the ripple does, which is the whole point.
  const shallow = mk(36, 3e5);
  const high = E.stageSystem({ A: 'EPC2361', NA: 2, ind: p }, shallow, {});
  assert.ok(high.sat.Leff > 0.95 * p.L, 'a shallow bias must leave L nearly alone: ' + high.sat.Leff);
  assert.ok(high.sat.Leff > low.sat.Leff, 'and hold more inductance than the deep-bias case');
  // The caller does NOT have to bind op.L: a selected filter inductor IS the
  // inductance.  Getting this wrong silently ran the fixed point at zero ripple,
  // which is why it is asserted rather than assumed.
  const noL = Object.assign(mk(120, 1e5), { L: null });
  const r = E.stageSystem({ A: 'EPC2361', NA: 2, ind: p }, noL, {});
  assert.ok(r.dILind > 0, 'op.L must be bound from the selected inductor');
  assertClose(r.dILind, r.sat.ipp, 'and equal the saturated ripple', 1e-12);
});

test('a saturating series choke is solved in the 3-phase case too', () => {
  const p = E.INDUCTORS.WE_7443634700;
  const op = Object.assign(E.defaultOp('threephase'),
    { Vdc: 58, Irms: 30, M: 1, PF: 0.9, fsw: 25e3, Ls: 3.73e-6, f1: 200 });
  const withChoke = E.stageSystem({ A: 'EPC2361', NA: 2, ind: p }, op, {});
  const noChoke = E.stageSystem({ A: 'EPC2361', NA: 2 }, op, {});
  assert.ok(withChoke.sat && withChoke.sat.family === '3-phase', 'the choke must be solved');
  // The choke cuts the ripple, and it must do so with LESS inductance than its
  // nominal value, because the bias has already rolled it off.
  assert.ok(withChoke.ipp < noChoke.ipp, 'a choke must reduce the 3-phase ripple');
  assert.ok(withChoke.sat.Leff < p.L,
    'the choke must show roll-off: ' + withChoke.sat.Leff + ' vs ' + p.L);
  // The solved total inductance is winding + the effective choke.
  assertClose(withChoke.sat.Ltot, op.Ls + withChoke.sat.Leff, 'total Ls', 1e-12);
  // No choke selected: nothing to solve, and the winding alone sets the ripple.
  assert.equal(noChoke.sat, null);
});

/* ----------------------------------------------------------- stage system */
test('the DC link draws the analytic bus current and carries a real ripple', () => {
  const Vdc = 58, M = 1, Irms = 80, PF = 0.9;
  const dl = E.dcLinkCurrent(Vdc, M, 25000, Irms, PF);
  // The carrier-averaged bus current of a 3-phase inverter is P_out/Vdc.  This
  // is the check that ties the DC-link model to the same SVPWM duties and the
  // same power convention the rest of the tool uses.
  const Pout = 3 * (M * Vdc / (2 * Math.SQRT2)) * Irms * PF;
  assertClose(dl.Idc_avg, Pout / Vdc, 'Idc_avg', 1e-9);
  assert.ok(dl.Icap_rms > 0, 'the capacitor must carry ripple');
  // For SVPWM at M = 1 and cos(phi) = 0.9 the classic ratio is around half the
  // phase current; assert the band rather than a number no anchor pins.
  const ratio = dl.Icap_rms / Irms;
  assert.ok(ratio > 0.3 && ratio < 0.7, 'Icap/Iph was ' + ratio);
  assert.ok(dl.dvPerFarad > 0, 'the bus current ripple must charge the capacitor');
  assertClose(dl.phi, Math.acos(0.9), 'phi', 1e-12);
  // Zero current means zero capacitor current and no ripple.
  const z = E.dcLinkCurrent(58, 1, 25000, 0, 0.9);
  assert.equal(z.Icap_rms, 0);
  assert.equal(z.dvPerFarad, 0);
  assert.throws(() => E.dcLinkCurrent(0, 1, 25000, 80, 0.9), /Vdc/);
});

test('the system budget adds up and reports its efficiency against the whole load', () => {
  const sel = { A: 'EPC2361', NA: 3, mot: E.MOTORS.LEHNER_7050_10, cap: E.CAPS.ceramic_2u2, ind: null };
  const op = Object.assign(E.defaultOp('threephase'),
    { Vdc: 58, Irms: 80, M: 1, PF: 0.9, fsw: 25000, Ls: 3.73e-6, f1: 300 });
  const r = E.stageSystem(sel, op, {});
  let sum = 0;
  for (const k of Object.keys(r.terms)) sum += r.terms[k];
  assertClose(r.total, sum, 'total must be the sum of its terms', 1e-12);
  assert.ok(r.terms.machine > 0, 'a 3-phase drive must count the machine');
  assert.ok(r.terms.fet > 0 && r.terms.capEsr > 0, 'and the FETs and the DC link');
  assertClose(r.eff, r.Pout / (r.Pout + r.total), 'efficiency', 1e-12);
  assert.ok(r.eff > 0.5 && r.eff < 1, 'efficiency ' + r.eff);
  // The machine dominates here, which is the honest picture at 90 A pk-pk of
  // ripple: the FETs are 3% of the total.
  assert.ok(r.terms.machine > 10 * r.terms.fet, 'the machine must dominate at this ripple');
  // The profile decides the terms: a DC-DC build has no machine term at all.
  const dsel = { A: 'EPC23102', NA: 1, ind: E.INDUCTORS.WE_74437636351012, cap: E.CAPS.ceramic_10u };
  const dop = Object.assign(E.defaultOp('boost'), { Vin: 25, Vout: 55, Pout: 110, fsw: 200e3 });
  const dr = E.stageSystem(dsel, dop, {});
  assert.equal(dr.terms.machine, undefined, 'a DC-DC build must have no machine term');
  assert.ok(dr.terms.ind > 0 && dr.terms.capEsr > 0, 'but it must count inductor and capacitor loss');
  assert.equal(dr.nodes.length, 2, 'both DC-DC nodes are reported');
  assert.equal(dr.nodes.find(n => n.node === 'in').kind, 'smooth');
  assert.equal(dr.nodes.find(n => n.node === 'out').kind, 'pulsed');
});

test('the FET half reduces exactly to the comparator when there is no ripple', () => {
  const op = Object.assign(E.defaultOp('threephase'), { Vdc: 58, Irms: 80, M: 1, PF: 0.9, fsw: 25000 });
  // 1 kH of phase inductance makes the ripple ~5e-8 A, i.e. negligible at double
  // precision, so the design workspace must land on the comparator's number.
  const big = Object.assign({}, op, { Ls: 1e3 });
  const r = E.stageSystem({ A: 'EPC2361', NA: 3 }, big, {});
  const rc = E.computeLosses(E.PARTS.EPC2361, big, 3, { tempMode: 'converged' });
  assertClose(r.terms.fet, rc.total, 'zero-ripple FET loss', 1e-12);
  // And with real ripple it must NOT match: the winding current is bigger.
  const r2 = E.stageSystem({ A: 'EPC2361', NA: 3 }, Object.assign({}, op, { Ls: 3.73e-6 }), {});
  assert.ok(r2.terms.fet > rc.total, 'ripple must raise FET conduction loss');
  assert.ok(r2.ipp > 80, 'and the winding gives ~90 A pk-pk of ripple: ' + r2.ipp);
});

test('the system loss has an interior switching-frequency optimum, unlike FETs alone', () => {
  // The comparator says plainly that it has NO interior fsw optimum, because
  // with FET losses alone the curve is monotonic.  Add the machine and it does:
  // raising fsw costs switching loss and buys lower ripple copper and iron.
  const sel = { A: 'EPC2361', NA: 3, mot: E.MOTORS.LEHNER_7050_10, cap: E.CAPS.ceramic_2u2 };
  const op = Object.assign(E.defaultOp('threephase'),
    { Vdc: 58, Irms: 80, M: 1, PF: 0.9, Ls: 3.73e-6, f1: 300 });
  const sw = E.sweepStage(sel, op, {}, 5000, 300000, 80);
  const i = sw.points.findIndex(p => Math.abs(p.fsw - sw.fopt) < 1e-6);
  assert.ok(i > 0, 'the optimum must not be the left edge: ' + sw.fopt);
  assert.ok(i < sw.points.length - 1, 'the optimum must not be the right edge: ' + sw.fopt);
  // ...and both neighbours must be worse, which is what "interior minimum" means.
  assert.ok(sw.points[i - 1].total > sw.best, 'left neighbour is not worse');
  assert.ok(sw.points[i + 1].total > sw.best, 'right neighbour is not worse');
  assert.ok(sw.points[0].total > sw.best, 'the low-frequency end must be worse');
  assert.ok(sw.points[sw.points.length - 1].total > sw.best, 'the high-frequency end must be worse');
  // The FET-only sweep over the same range is monotonic, which is the contrast
  // the README draws.
  const fetOnly = E.sweepFsw(E.PARTS.EPC2361, op, 3, 5000, 300000, 20, {});
  assert.equal(fetOnly.fopt, 5000, 'FET losses alone must be monotonic in fsw');
  // The DC-DC case is worth pinning separately, because it is where modelling
  // saturation changes the SHAPE of the answer.  With a fixed NOMINAL inductance
  // the total is monotonic in fsw and the optimum sits at the low edge.  Model
  // the roll-off and it is not monotonic at all: at low fsw the ripple is large,
  // the peak current is high, the core rolls off, and the ripple grows further,
  // so the core loss runs away -- 18x the optimum at 5 kHz on this build.  That
  // feedback pushes the optimum inward, which is exactly what the nominal-L
  // model could not show.
  const dsel = { A: 'EPC23102', NA: 1, ind: E.INDUCTORS.WE_74437636351012, cap: E.CAPS.ceramic_10u };
  const dop = Object.assign(E.defaultOp('boost'), { Vin: 25, Vout: 55, Pout: 110 });
  const dsw = E.sweepStage(dsel, dop, {}, 5e3, 300e3, 40);
  const di = dsw.points.findIndex(p => Math.abs(p.fsw - dsw.fopt) < 1e-6);
  assert.ok(di > 0, 'with saturation the DC-DC optimum must not be the low edge: ' + dsw.fopt);
  assert.ok(di < dsw.points.length - 1, 'nor the high edge: ' + dsw.fopt);
  assert.ok(dsw.points[0].total > 3 * dsw.best,
    'low fsw must be strongly penalised once the core rolls off: ' +
    dsw.points[0].total + ' vs ' + dsw.best);
  // ...and the mechanism is directly visible: the inductance really does fall.
  const low = E.stageSystem(dsel, Object.assign({}, dop, { fsw: 5e3 }), {});
  assert.ok(low.sat && low.sat.Leff < 0.95 * low.sat.Lnom,
    'the low-frequency end must show a rolled-off inductance, got ' + (low.sat && low.sat.Leff));
  assert.ok(low.dILind > low.sat.ipp * 0.99, 'the reported ripple must be the saturated one');
  const mid = E.stageSystem(dsel, Object.assign({}, dop, { fsw: 150e3 }), {});
  assert.ok(mid.sat.Leff > 0.97 * mid.sat.Lnom, 'at a sane carrier the core is barely rolled off');
});

test('the feasibility map marks the constraint that failed, not just the loss', () => {
  const sel = { A: 'EPC2361', NA: 3, mot: E.MOTORS.LEHNER_7050_10, cap: E.CAPS.ceramic_2u2 };
  const op = Object.assign(E.defaultOp('threephase'),
    { Vdc: 58, Irms: 80, M: 1, PF: 0.9, f1: 300 });
  const fsws = [20000, 60000, 120000], Ls = [1e-6, 3.73e-6, 20e-6, 100e-6];
  const rows = E.feasibility(sel, op, {}, fsws, Ls, { ipp: 40 });
  assert.equal(rows.length, 3);
  assert.equal(rows[0].length, 4);
  const at = (f, L) => rows[fsws.indexOf(f)][Ls.indexOf(L)];
  // 1 uH is far too little inductance for a 40 A pk-pk target at any frequency
  // here, so those cells must fail on ripple and say so.
  assert.equal(at(20000, 1e-6).feasible, false);
  assert.ok(at(20000, 1e-6).why.includes('ripple'), 'why: ' + at(20000, 1e-6).why);
  // 100 uH at 120 kHz is comfortably inside every constraint.
  assert.equal(at(120000, 100e-6).feasible, true, 'why: ' + at(120000, 100e-6).why);
  assert.deepEqual(at(120000, 100e-6).why, []);
  // The ripple target is a hard frontier: ipp must fall monotonically with fsw
  // down each column, and with Ls along each row.
  for (let j = 0; j < Ls.length; j++)
    assert.ok(at(120000, Ls[j]).ipp < at(20000, Ls[j]).ipp, 'ipp must fall with fsw');
  for (let i = 0; i < fsws.length; i++)
    assert.ok(at(fsws[i], 100e-6).ipp < at(fsws[i], 3.73e-6).ipp, 'ipp must fall with Ls');
});

/* ---------------------------------------------- design-workspace regressions */
test('countCap gates only the capacitor ESR loss, not its sizing answers', () => {
  const cap = E.CAPS.ceramic_2u2;
  const dop = Object.assign(E.defaultOp('buck'), { Vin: 48, Vout: 12, Pout: 240, fsw: 100e3, L: 1e-4 });
  const on = E.stageSystem({ A: 'EPC2361', NA: 1, cap, countCap: true }, dop, {});
  const off = E.stageSystem({ A: 'EPC2361', NA: 1, cap, countCap: false }, dop, {});
  assert.ok(on.terms.capEsr > 0, 'the bank must carry loss when counted');
  assert.equal(off.terms.capEsr, undefined, 'unticking must remove the term');
  assertClose(off.total, on.total - on.terms.capEsr, 'the total drops by exactly the cap loss', 1e-12);
  assert.deepEqual(off.nodes.map(n => n.r.dvpp), on.nodes.map(n => n.r.dvpp),
    'the per-node voltage ripple must still be computed when the loss is not counted');
  // An absent flag keeps the historical behaviour (counted).
  const def = E.stageSystem({ A: 'EPC2361', NA: 1, cap }, dop, {});
  assertClose(def.total, on.total, 'countCap defaults to counting', 1e-12);
  // The 3-phase DC-link sizing answer must survive the same toggle.
  const op3 = Object.assign(E.defaultOp('threephase'),
    { Vdc: 58, Irms: 80, M: 1, PF: 0.9, fsw: 25e3, Ls: 3.73e-6 });
  const a3 = E.stageSystem({ A: 'EPC2361', NA: 2, cap, countCap: true }, op3, {});
  const b3 = E.stageSystem({ A: 'EPC2361', NA: 2, cap, countCap: false }, op3, {});
  assert.ok(a3.dcPerFarad > 0 && b3.dcPerFarad === a3.dcPerFarad,
    'the DC-link excursion per farad must not depend on counting the ESR loss');
  assertClose(b3.total, a3.total - a3.terms.capEsr, 'and the same holds for the term', 1e-12);
});

test('a 3-phase series choke is added exactly once, saturating or not', () => {
  const p = E.INDUCTORS.WE_7443634700;
  const wind = 3.73e-6;
  const op = Object.assign(E.defaultOp('threephase'),
    { Vdc: 58, Irms: 30, M: 1, PF: 0.9, fsw: 25e3, Ls: wind, f1: 200 });
  const r = E.stageSystem({ A: 'EPC2361', NA: 2, ind: p }, op, {});
  assert.ok(r.sat, 'the seeded choke must be solved');
  assertClose(r.sat.Ltot, wind + r.sat.Leff, 'total Ls = winding + the effective choke, once', 1e-12);
  assert.ok(r.sat.Ltot < wind + p.L, 'roll-off means less than winding + the nominal choke');
  // A hand-entered choke carries no bias curve; it must still contribute its
  // nominal inductance rather than being silently dropped.
  const custom = { PN: 'CUSTOM (entered)', L: 20e-6, DCR: 1e-3, Isat10: 120, Isat30: 140,
                   Irated: 100, kAc: 2e-5, aAc: 0.7, bAc: 2.0, cAc: -0.05 };
  const rc = E.stageSystem({ A: 'EPC2361', NA: 2, ind: custom }, op, {});
  assert.equal(rc.sat, null, 'no bias curve means no roll-off model');
  assert.ok(rc.ipp < E.stageSystem({ A: 'EPC2361', NA: 2 }, op, {}).ipp,
    'and the custom choke must still cut the ripple');
});

test('the feasibility map checks the DC-DC capacitor voltage ripple too', () => {
  const sel = { A: 'EPC2361', NA: 1, cap: E.CAPS.ceramic_2u2 };
  const op = Object.assign(E.defaultOp('buck'), { Vin: 48, Vout: 12, Pout: 240, fsw: 100e3 });
  const tight = E.feasibility(sel, op, {}, [100e3], [1e-4], { ipp: 1e9, dvpp: 1e-6 });
  assert.ok(tight[0][0].why.includes('dv'), 'a 1 uV target cannot be met: ' + tight[0][0].why);
  const loose = E.feasibility(sel, op, {}, [100e3], [1e-4], { ipp: 1e9, dvpp: 1e3 });
  assert.ok(!loose[0][0].why.includes('dv'), 'a loose target must clear: ' + loose[0][0].why);
});

test('out-of-range duty is clamped and flagged, never NaN', () => {
  const op = Object.assign(E.defaultOp('buck'), { Vin: 12, Vout: 48, Pout: 240, fsw: 100e3, L: 1e-4 });
  const r = E.stageSystem(
    { A: 'EPC2361', NA: 1, cap: E.CAPS.ceramic_2u2, ind: E.INDUCTORS.WE_7443634700 }, op, {});
  assert.ok(Number.isFinite(r.total) && r.total >= 0, 'total ' + r.total);
  assert.ok(r.warnings.some(w => w.code === 'duty_range'), 'the clamp must be flagged');
  r.nodes.forEach(n => assert.ok(Number.isFinite(n.r.dvpp) && n.r.dvpp >= 0, 'dvpp ' + n.r.dvpp));
  // The inverse has no meaning outside (0,1), and a blank required field is refused
  // rather than silently returning Infinity/NaN.
  assert.throws(() => E.dcRequiredL(op, 'buck', 2), /duty/);
  assert.throws(() => E.computeLosses(E.PARTS.EPC2361,
    Object.assign(E.defaultOp('buck'), { Vout: null }), 1, {}), /V_out/);
});

test('fsw = 0 and zero current still yield finite FOM rows', () => {
  const z = Object.assign(E.defaultOp('buck'), { fsw: 0, Vin: 48, Vout: 12, Pout: 240 });
  const c = E.compare(E.PARTS.EPC2361, E.PARTS.IRF7759, z, { A: 1, B: 1 }, {});
  assert.ok(Number.isFinite(c.fom.A.Nint) && c.fom.A.Nint >= 1, 'Nint ' + c.fom.A.Nint);
  assert.equal(c.fom.A.penaltyPct, null, 'no finite optimum means no penalty figure');
  assert.ok(Number.isFinite(c.eachOpt[0].total) && Number.isFinite(c.eachOpt[1].total),
    'the each-at-own-Nopt view must stay finite');
  const z2 = Object.assign(E.defaultOp('threephase'), { Irms: 0, M: 0, fsw: 40e3 });
  const c2 = E.compare(E.PARTS.EPC2361, E.PARTS.IRF7759, z2, { A: 1, B: 1 }, {});
  assert.ok(Number.isFinite(c2.fom.A.Nopt) && c2.fom.A.Nopt >= 1, 'Nopt ' + c2.fom.A.Nopt);
  assert.equal(c2.fom.A.penaltyPct, null);
});

test('the saturation constraint uses the ripple peak, not the fundamental peak', () => {
  const op = Object.assign(E.defaultOp('threephase'),
    { Vdc: 58, Irms: 10, M: 1, PF: 0.9, fsw: 25e3, Ls: 1e-6 });
  const sel = { A: 'EPC2361', NA: 2, ind: E.INDUCTORS.WE_7443631500 };  // Isat10 = 19 A
  const r = E.stageSystem(sel, op, {});
  assert.ok(r.ipeak > sel.ind.Isat10, 'the ripple peak must exceed Isat10: ' + r.ipeak);
  const rows = E.feasibility(sel, op, {}, [25e3], [1e-6], { ipp: 1e9 });
  assert.ok(rows[0][0].why.includes('Isat'), 'the map must flag it: ' + rows[0][0].why);
});

test('a zero ripple or voltage target is no constraint on the feasibility map', () => {
  const sel = { A: 'EPC2361', NA: 1, cap: E.CAPS.ceramic_2u2 };
  const op = Object.assign(E.defaultOp('buck'), { Vin: 48, Vout: 12, Pout: 240, fsw: 100e3 });
  const rows = E.feasibility(sel, op, {}, [100e3], [1e-4], { ipp: 0, dvpp: 0 });
  assert.ok(!rows[0][0].why.includes('ripple') && !rows[0][0].why.includes('dv'),
    'zero targets must not hatch every cell: ' + rows[0][0].why);
});

test('a series choke still works with a zero winding inductance', () => {
  const op = Object.assign(E.defaultOp('threephase'),
    { Vdc: 58, Irms: 30, M: 1, PF: 0.9, fsw: 25e3, Ls: 0, f1: 200 });
  const withChoke = E.stageSystem({ A: 'EPC2361', NA: 2, ind: E.INDUCTORS.WE_7443634700 }, op, {});
  assert.ok(withChoke.ipp > 0, 'the choke must carry the ripple: ' + withChoke.ipp);
  assert.ok(!withChoke.warnings.some(w => w.code === 'no_ls'),
    'Ls = 0 but the choke is present, so there is ripple');
});

test('a DC-DC design with no filter inductor warns instead of reporting zero ripple', () => {
  const op = Object.assign(E.defaultOp('buck'), { Vin: 48, Vout: 12, Pout: 240, fsw: 100e3, L: null });
  const bare = E.stageSystem({ A: 'EPC2361', NA: 1 }, op, {});
  assert.equal(bare.ipp, 0);
  assert.ok(bare.warnings.some(w => w.code === 'no_filter_L'),
    'must warn: ' + JSON.stringify(bare.warnings.map(w => w.code)));
  const withInd = E.stageSystem({ A: 'EPC2361', NA: 1, ind: E.INDUCTORS.WE_7443634700 }, op, {});
  assert.ok(!withInd.warnings.some(w => w.code === 'no_filter_L'), 'and clear once a part is selected');
  assert.ok(withInd.ipp > 0);
});


